import { blockVersion, type Lesson, type Part } from '@interactive-textbook/schema';
import type { Pitch } from '@interactive-textbook/subject-music';

const p = (step: Pitch['step'], octave: number, alter: Pitch['alter'] = 0): Pitch => ({ step, alter, octave });
const F3=p('F',3),G3=p('G',3),A3=p('A',3),B3=p('B',3);
const C4=p('C',4),D4=p('D',4),E4=p('E',4),F4=p('F',4),G4=p('G',4),A4=p('A',4),B4=p('B',4);
const Gs4=p('G',4,1);
const I=[C4,E4,G4], ii=[D4,F4,A4], iii=[E4,G4,B4], IV=[F3,A3,C4], V=[G3,B3,D4], vi=[A3,C4,E4], vii=[B3,D4,F4];
const i=[A3,C4,E4], v=[E4,G4,B4], minV=[E4,Gs4,B4], leadingDim=[Gs4,B4,D4], VII=[G3,B3,D4];

interface Draft { key:string; legacy:string; title:string; summary:string; objective:string; markdown:string; groups:Pitch[][]; activityTitle:string; prompt:string; options:Array<{id:string;label:string}>; answer:string; explanation:string; items:string[]; prerequisiteRefs?:string[]; }
function lesson(d:Draft):Lesson { const prefix=`harmony.${d.key}`, objective=`${prefix}.objective`, data=`${prefix}.data.examples`, check=`${prefix}.block.check`;
  return { id:`${prefix}.lesson`, title:`${d.legacy}. ${d.title}`, summary:d.summary, estimatedMinutes:10, prerequisiteRefs:d.prerequisiteRefs,
    objectives:[{id:objective,title:d.objective}], data:[{id:data,subject:'music',kind:'pitch-groups',value:d.groups}], blocks:[
      {id:`${prefix}.block.concept`,blockVersion,type:'content.markdown',objectiveRefs:[objective],data:{markdown:d.markdown}},
      {id:`${prefix}.block.examples`,blockVersion,type:'activity.subject',objectiveRefs:[objective],dataRefs:[data],data:{subject:'music',tool:'pitch-pair-viewer',title:d.activityTitle,input:{pairs:d.groups,interactive:false}}},
      {id:check,blockVersion,type:'assessment.multiple-choice',objectiveRefs:[objective],data:{prompt:d.prompt,options:d.options,answer:d.answer,explanation:d.explanation}},
      {id:`${prefix}.block.summary`,blockVersion,type:'content.summary',objectiveRefs:[objective],data:{items:d.items}},
    ],completion:{type:'required-blocks',blockRefs:[check]}};
}
const opts=(...labels:string[])=>labels.map((label,index)=>({id:`o${index+1}`,label}));

export const batchCPart6:Part={id:'harmony.part.diatonic',title:'PART 6. 다이어토닉 코드',lessons:[
  lesson({key:'lesson.major-diatonic',legacy:'6-1',title:'장조의 다이어토닉 코드',summary:'장음계 각 음 위에 3화음을 쌓아 일곱 화음을 만듭니다.',objective:'장조의 일곱 다이어토닉 3화음과 성질을 설명한다.',prerequisiteRefs:['harmony.lesson.seventh-resolution.lesson'],markdown:'C장조의 각 음 위에 음계음만으로 3도를 쌓으면 **I–ii–iii–IV–V–vi–vii°**가 됩니다. 성질은 장–단–단–장–장–단–감 순서입니다.',groups:[I,ii,iii,IV,V,vi,vii],activityTitle:'C장조의 일곱 다이어토닉 화음',prompt:'장조의 다섯 번째 다이어토닉 3화음은?',options:opts('V 장3화음','v 단3화음','v° 감3화음'),answer:'o1',explanation:'장조의 V는 장3화음이며 도미넌트 기능을 가집니다.',items:['장조의 화음 성질은 장–단–단–장–장–단–감입니다.','대문자는 장화음, 소문자는 단화음을 뜻합니다.','감화음에는 °를 붙입니다.']}),
  lesson({key:'lesson.minor-diatonic',legacy:'6-2',title:'단조의 다이어토닉 코드',summary:'자연단음계와 화성단음계의 화음 차이를 비교합니다.',objective:'단조에서 7음 변화가 V와 vii°에 미치는 영향을 설명한다.',prerequisiteRefs:['harmony.lesson.major-diatonic.lesson'],markdown:'자연단음계에서는 v가 단화음이고 VII이 장화음이지만, 화성단음계는 7음을 올려 **V 장화음과 vii°**를 만듭니다. 이끎음이 생겨 i로 향하는 힘이 강해집니다.',groups:[i,v,minV,VII,leadingDim],activityTitle:'A자연단음계의 v·VII과 화성단음계의 V·vii° 비교',prompt:'A화성단음계에서 G♯ 때문에 장화음이 되는 것은?',options:opts('V(E–G♯–B)','iv(D–F–A)','III(C–E–G)'),answer:'o1',explanation:'올라간 7음 G♯은 E화음의 장3음이 되어 V 장화음을 만듭니다.',items:['자연단음계의 v는 단화음이고 VII은 장화음입니다.','화성단음계의 V는 장화음이고 vii°는 감화음입니다.','이끎음은 으뜸화음으로의 해결을 강화합니다.']}),
  lesson({key:'lesson.roman-analysis',legacy:'6-3',title:'로마숫자 분석',summary:'조성 안에서 근음의 위치와 화음 성질을 함께 표시합니다.',objective:'화음의 근음·성질·전위를 로마숫자로 분석한다.',prerequisiteRefs:['harmony.lesson.minor-diatonic.lesson'],markdown:'로마숫자는 **조성 안의 음계 위치**를 나타냅니다. 먼저 조성을 찾고, 화음의 근음과 성질을 확인한 뒤 전위 숫자를 붙입니다.',groups:[I,IV,V,vi],activityTitle:'C장조 I–IV–V–vi 비교',prompt:'C장조에서 A–C–E는?',options:opts('vi','IV','ii'),answer:'o1',explanation:'A는 C장조의 6음이고 A–C–E는 단3화음이므로 vi입니다.',items:['먼저 조성을 정합니다.','근음의 음계 위치를 찾습니다.','대·소문자와 전위 숫자로 성질과 배치를 표시합니다.']}),
  lesson({key:'lesson.function-basics',legacy:'6-4',title:'기능의 기초',summary:'화음을 안정·이동·긴장의 세 기능으로 묶습니다.',objective:'다이어토닉 화음을 T·S·D 기능군으로 분류한다.',prerequisiteRefs:['harmony.lesson.roman-analysis.lesson'],markdown:'기능화성은 화음을 **Tonic(T), Subdominant(S), Dominant(D)**로 묶습니다. T는 안정, S는 이탈과 전개, D는 긴장과 귀환을 담당합니다.',groups:[I,IV,V],activityTitle:'T–S–D 대표 화음 비교',prompt:'가장 강하게 I로 해결하려는 기능은?',options:opts('Dominant','Tonic','Subdominant'),answer:'o1',explanation:'Dominant는 이끎음과 긴장을 포함해 Tonic으로 해결하려 합니다.',items:['T는 안정의 중심입니다.','S는 중심에서 멀어지게 합니다.','D는 긴장을 만들고 T로 돌아갑니다.']})
]};

export const batchCPart7:Part={id:'harmony.part.functions',title:'PART 7. 화성 기능',lessons:[
  lesson({key:'lesson.tonic-function',legacy:'7-1',title:'Tonic',summary:'I를 중심으로 안정과 휴식의 기능을 듣습니다.',objective:'Tonic 기능을 가진 화음과 안정감을 식별한다.',prerequisiteRefs:['harmony.lesson.function-basics.lesson'],markdown:'Tonic은 조성의 중심과 안정감을 나타냅니다. **I**가 가장 강한 Tonic이며, 공통음을 가진 vi와 iii도 문맥에 따라 대리할 수 있습니다.',groups:[I,vi,iii],activityTitle:'I·vi·iii의 안정감 비교',prompt:'가장 강한 Tonic 기능은?',options:opts('I','vi','iii'),answer:'o1',explanation:'I는 으뜸음을 근음으로 하여 조성의 중심을 가장 분명히 보여줍니다.',items:['I는 중심 Tonic입니다.','vi와 iii는 제한적으로 대리합니다.','Tonic은 시작과 도착에서 안정감을 줍니다.']}),
  lesson({key:'lesson.subdominant-function',legacy:'7-2',title:'Subdominant',summary:'IV와 ii가 중심에서 벗어나 진행을 여는 방식을 확인합니다.',objective:'Subdominant 기능의 IV와 ii를 구별한다.',prerequisiteRefs:['harmony.lesson.tonic-function.lesson'],markdown:'Subdominant는 Tonic에서 벗어나 Dominant로 향하도록 준비합니다. 대표 화음은 **IV와 ii**이며, 둘은 공통음과 순차 진행으로 연결됩니다.',groups:[IV,ii],activityTitle:'IV와 ii의 준비 기능 비교',prompt:'C장조에서 대표적인 Subdominant 화음은?',options:opts('IV와 ii','I와 vi','V와 vii°'),answer:'o1',explanation:'IV와 ii는 대표적인 Subdominant 기능군입니다.',items:['IV와 ii는 S 기능입니다.','S는 T에서 D로 가는 흐름을 준비합니다.','베이스와 공통음이 연결감을 만듭니다.']}),
  lesson({key:'lesson.dominant-function',legacy:'7-3',title:'Dominant',summary:'V와 vii°의 이끎음이 Tonic으로 향하는 힘을 듣습니다.',objective:'Dominant 기능의 긴장음과 해결 방향을 설명한다.',prerequisiteRefs:['harmony.lesson.subdominant-function.lesson'],markdown:'Dominant는 가장 강한 긴장 기능입니다. **V와 vii°**에는 이끎음이 포함되어 I로 향하며, V7의 7음은 아래로 해결됩니다.',groups:[V,vii,[G3,B3,D4,F4],I],activityTitle:'V·vii°·V7에서 I로',prompt:'C장조에서 Dominant 기능군은?',options:opts('V와 vii°','IV와 ii','I와 vi'),answer:'o1',explanation:'V와 vii°는 이끎음 B를 포함해 I로 향합니다.',items:['V와 vii°는 D 기능입니다.','이끎음은 으뜸음으로 올라갑니다.','V7의 7음은 보통 아래로 해결됩니다.']}),
  lesson({key:'lesson.function-connection',legacy:'7-4',title:'기능의 연결',summary:'T–S–D–T의 방향성을 실제 화음으로 연결합니다.',objective:'기본 기능 진행 T–S–D–T를 로마숫자로 구성한다.',prerequisiteRefs:['harmony.lesson.dominant-function.lesson'],markdown:'가장 기본적인 기능 흐름은 **T–S–D–T**입니다. C장조에서는 I–IV–V–I 또는 I–ii–V–I처럼 구현할 수 있습니다.',groups:[I,IV,V,I],activityTitle:'I–IV–V–I 기능 흐름',prompt:'T–S–D–T에 맞는 진행은?',options:opts('I–IV–V–I','I–V–IV–I','V–I–ii–IV'),answer:'o1',explanation:'I는 T, IV는 S, V는 D, 마지막 I는 T입니다.',items:['기능은 개별 코드보다 방향을 설명합니다.','T–S–D–T가 기본 흐름입니다.','ii는 IV를 대신해 S 기능을 만들 수 있습니다.']}),
  lesson({key:'lesson.function-analysis',legacy:'7-5',title:'기능 분석',summary:'코드 진행을 로마숫자와 T·S·D로 두 번 읽습니다.',objective:'주어진 진행의 로마숫자와 기능 흐름을 분석한다.',prerequisiteRefs:['harmony.lesson.function-connection.lesson'],markdown:'기능 분석은 조성과 로마숫자를 확인한 뒤 각 화음을 T·S·D로 묶습니다. 대리화음이 있어도 **긴장과 해결의 방향**을 우선 봅니다.',groups:[vi,ii,V,I],activityTitle:'vi–ii–V–I 기능 분석',prompt:'C장조 vi–ii–V–I의 기능 흐름은?',options:opts('T–S–D–T','S–T–D–S','D–S–T–D'),answer:'o1',explanation:'vi는 T 대리, ii는 S, V는 D, I는 T입니다.',items:['조성을 먼저 확인합니다.','로마숫자 다음 기능을 붙입니다.','대리화음도 진행 방향 안에서 해석합니다.']})
]};

export const batchCPart8Before:Lesson[]=[
  lesson({key:'lesson.authentic-cadence',legacy:'8-1',title:'정격종지',summary:'V–I의 강한 해결과 완전정격종지 조건을 확인합니다.',objective:'정격종지의 V–I 진행과 마침감을 구별한다.',prerequisiteRefs:['harmony.lesson.function-analysis.lesson'],markdown:'정격종지는 **V–I**로 끝납니다. 두 화음이 기본형이고 소프라노가 으뜸음으로 끝나면 완전정격종지이며, 그 밖은 불완전정격종지입니다.',groups:[V,I],activityTitle:'V–I 정격종지',prompt:'정격종지의 기본 진행은?',options:opts('V–I','IV–I','I–V'),answer:'o1',explanation:'Dominant V가 Tonic I로 해결되는 진행입니다.',items:['정격종지는 V–I입니다.','완전정격종지는 두 화음이 기본형입니다.','강한 마침감을 만듭니다.']}),
  lesson({key:'lesson.half-cadence',legacy:'8-2',title:'반종지',summary:'V에서 멈춰 계속될 듯한 열린 느낌을 확인합니다.',objective:'마지막 화음이 V인 반종지를 식별한다.',prerequisiteRefs:['harmony.lesson.authentic-cadence.lesson'],markdown:'반종지는 앞의 화음과 관계없이 **V에서 끝나는 종지**입니다. 긴장이 해결되지 않아 질문이나 쉼표처럼 계속될 느낌을 줍니다.',groups:[I,V],activityTitle:'I–V 반종지',prompt:'반종지의 마지막 화음은?',options:opts('V','I','IV'),answer:'o1',explanation:'반종지는 Dominant V에서 멈춥니다.',items:['반종지는 V에서 끝납니다.','긴장이 남아 열린 느낌을 줍니다.','악구 중간에 자주 사용됩니다.']}),
  lesson({key:'lesson.plagal-cadence',legacy:'8-3',title:'변격종지',summary:'IV–I의 부드러운 마침을 정격종지와 비교합니다.',objective:'IV–I 변격종지의 소리와 기능 흐름을 설명한다.',prerequisiteRefs:['harmony.lesson.half-cadence.lesson'],markdown:'변격종지는 **IV–I**로 끝나며 S에서 T로 직접 이동합니다. 정격종지보다 부드럽고 찬송가의 아멘 진행으로 익숙합니다.',groups:[IV,I],activityTitle:'IV–I 변격종지',prompt:'변격종지의 진행은?',options:opts('IV–I','V–I','V–vi'),answer:'o1',explanation:'Subdominant IV가 Tonic I로 이동합니다.',items:['변격종지는 IV–I입니다.','S–T의 부드러운 마침입니다.','정격종지와 해결 강도가 다릅니다.']}),
  lesson({key:'lesson.deceptive-cadence',legacy:'8-4',title:'기만종지',summary:'V가 예상한 I 대신 vi로 가는 방향 전환을 듣습니다.',objective:'V–vi 기만종지와 예상의 어긋남을 식별한다.',prerequisiteRefs:['harmony.lesson.plagal-cadence.lesson'],markdown:'기만종지는 V가 예상되는 I 대신 **vi** 등 다른 화음으로 진행합니다. 일부 음은 자연스럽게 해결되지만 종결은 미뤄집니다.',groups:[V,vi],activityTitle:'V–vi 기만종지',prompt:'C장조의 대표적인 기만종지는?',options:opts('V–vi','V–I','IV–I'),answer:'o1',explanation:'V 다음에 I 대신 vi가 오면 대표적인 기만종지입니다.',items:['기만종지는 V 뒤에 I가 오지 않습니다.','대표형은 V–vi입니다.','예상을 비껴가 진행을 연장합니다.']})
];

export const batchCPart9:Part={id:'harmony.part.progressions',title:'PART 9. 화성 진행',lessons:[
  lesson({key:'lesson.basic-progression',legacy:'9-1',title:'기본 진행',summary:'기능의 방향을 지키는 짧은 진행을 구성합니다.',objective:'T–S–D–T에 맞는 기본 코드 진행을 선택한다.',prerequisiteRefs:['harmony.lesson.cadence'],markdown:'기본 진행은 기능의 방향과 성부의 자연스러운 연결을 함께 봅니다. **I–IV–V–I**는 조성의 중심, 이탈, 긴장, 해결을 분명히 보여줍니다.',groups:[I,IV,V,I],activityTitle:'I–IV–V–I 기본 진행',prompt:'가장 전형적인 기본 기능 진행은?',options:opts('I–IV–V–I','I–V–IV–iii','V–IV–ii–I'),answer:'o1',explanation:'T–S–D–T의 방향을 그대로 따릅니다.',items:['기능의 큰 방향을 먼저 봅니다.','공통음과 가까운 진행을 활용합니다.','마지막 D–T가 종결감을 만듭니다.']}),
  lesson({key:'lesson.stepwise-progression',legacy:'9-2',title:'순차 진행',summary:'근음이 2도씩 움직이는 연결의 선율성을 듣습니다.',objective:'근음의 순차 진행을 식별하고 장단점을 설명한다.',prerequisiteRefs:['harmony.lesson.basic-progression.lesson'],markdown:'순차 진행은 화음의 근음이 2도씩 움직입니다. 선율적이고 부드럽지만 기능 방향이 약할 수 있어 목적지 화음과 종지를 함께 설계합니다.',groups:[I,ii,iii,IV],activityTitle:'I–ii–iii–IV 순차 진행',prompt:'근음이 C–D–E–F로 움직이는 진행 유형은?',options:opts('순차 진행','순환 진행','반복 진행'),answer:'o1',explanation:'근음이 음계상 이웃한 음으로 한 단계씩 이동합니다.',items:['근음이 2도씩 움직입니다.','선율적인 연결을 만듭니다.','기능적 목적지를 함께 고려합니다.']}),
  lesson({key:'lesson.circle-progression',legacy:'9-3',title:'순환 진행',summary:'근음이 5도 하행하며 강하게 이어지는 흐름을 확인합니다.',objective:'5도 하행 순환 진행의 근음 패턴을 식별한다.',prerequisiteRefs:['harmony.lesson.stepwise-progression.lesson'],markdown:'순환 진행은 근음이 **5도 아래(또는 4도 위)**로 이어집니다. vi–ii–V–I처럼 각 화음이 다음 화음을 강하게 준비합니다.',groups:[vi,ii,V,I],activityTitle:'vi–ii–V–I 순환 진행',prompt:'vi–ii–V–I의 근음 진행 특징은?',options:opts('5도 하행','2도 상행','같은 근음 반복'),answer:'o1',explanation:'A–D–G–C는 각 단계가 5도 아래로 이어집니다.',items:['근음이 5도 아래로 이동합니다.','다음 화음으로의 추진력이 강합니다.','ii–V–I가 핵심 부분입니다.']}),
  lesson({key:'lesson.repeated-progression',legacy:'9-4',title:'반복 진행',summary:'짧은 화성 패턴을 반복해 구조와 기대를 만듭니다.',objective:'반복되는 화성 단위를 찾아 진행 구조를 설명한다.',prerequisiteRefs:['harmony.lesson.circle-progression.lesson'],markdown:'반복 진행은 같은 코드 묶음이나 기능 패턴이 되풀이됩니다. 기억하기 쉬운 구조를 만들지만, 음역·리듬·전위에 변화를 주면 단조로움을 줄일 수 있습니다.',groups:[I,vi,IV,V,I,vi,IV,V],activityTitle:'I–vi–IV–V 반복 패턴',prompt:'I–vi–IV–V–I–vi–IV–V에서 반복 단위는?',options:opts('I–vi–IV–V','I–vi','IV–V–I'),answer:'o1',explanation:'네 화음 I–vi–IV–V가 그대로 한 번 더 반복됩니다.',items:['반복 단위를 먼저 찾습니다.','반복은 예측 가능성과 통일감을 줍니다.','리듬과 전위로 변화를 만들 수 있습니다.']}),
  lesson({key:'lesson.common-progressions',legacy:'9-5',title:'일반적인 코드 진행',summary:'자주 쓰이는 진행을 기능과 소리로 비교합니다.',objective:'대표 코드 진행의 기능 흐름과 종지 방향을 설명한다.',prerequisiteRefs:['harmony.lesson.repeated-progression.lesson'],markdown:'자주 쓰이는 진행도 기능 원리로 설명할 수 있습니다. **I–V–vi–IV**, **ii–V–I**, **I–vi–IV–V**를 외우는 데 그치지 말고 베이스와 긴장·해결을 함께 듣습니다.',groups:[I,V,vi,IV,ii,V,I],activityTitle:'대표 진행 두 가지 비교',prompt:'재즈와 대중음악에서 널리 쓰이는 강한 종결 단위는?',options:opts('ii–V–I','I–ii–iii','IV–iii–ii'),answer:'o1',explanation:'ii–V–I는 S–D–T 기능을 압축한 대표 진행입니다.',items:['진행은 기능 흐름으로 이해합니다.','ii–V–I는 S–D–T입니다.','같은 진행도 전위·리듬·선율에 따라 달라집니다.']})
]};
