import { blockVersion, type Lesson, type Part } from '@interactive-textbook/schema';
import type { Pitch } from '@interactive-textbook/subject-music';

const p = (step: Pitch['step'], octave: number, alter: Pitch['alter'] = 0): Pitch => ({ step, alter, octave });
const A3 = p('A', 3); const B3 = p('B', 3); const C4 = p('C', 4); const D4 = p('D', 4); const E4 = p('E', 4); const F4 = p('F', 4); const G4 = p('G', 4);
const A4 = p('A', 4); const B4 = p('B', 4); const C5 = p('C', 5); const D5 = p('D', 5); const E5 = p('E', 5); const F5 = p('F', 5); const G5 = p('G', 5); const A5 = p('A', 5);
const Eb4 = p('E', 4, -1); const Bb4 = p('B', 4, -1); const Fs5 = p('F', 5, 1); const Gs5 = p('G', 5, 1);
const G3 = p('G', 3); const F3 = p('F', 3);

interface Draft { key: string; legacy: string; title: string; summary: string; objective: string; markdown: string; groups: Pitch[][]; activityTitle: string; prompt: string; options: Array<{ id: string; label: string }>; answer: string; explanation: string; items: string[]; prerequisiteRefs?: string[]; playbackMode?: 'sequential' | 'simultaneous' | 'progression'; }
function makeLesson(d: Draft): Lesson {
  const prefix = `harmony.${d.key}`; const objective = `${prefix}.objective`; const data = `${prefix}.data.examples`; const check = `${prefix}.block.check`;
  return { id: `${prefix}.lesson`, title: `${d.legacy}. ${d.title}`, summary: d.summary, estimatedMinutes: 10, prerequisiteRefs: d.prerequisiteRefs,
    objectives: [{ id: objective, title: d.objective }], data: [{ id: data, subject: 'music', kind: 'pitch-groups', value: d.groups }], blocks: [
      { id: `${prefix}.block.concept`, blockVersion, type: 'content.markdown', objectiveRefs: [objective], data: { markdown: d.markdown } },
      { id: `${prefix}.block.examples`, blockVersion, type: 'activity.subject', objectiveRefs: [objective], dataRefs: [data], data: { subject: 'music', tool: 'pitch-pair-viewer', title: d.activityTitle, input: { pairs: d.groups, interactive: false, playbackMode: d.playbackMode } } },
      { id: check, blockVersion, type: 'assessment.multiple-choice', objectiveRefs: [objective], data: { prompt: d.prompt, options: d.options, answer: d.answer, explanation: d.explanation } },
      { id: `${prefix}.block.summary`, blockVersion, type: 'content.summary', objectiveRefs: [objective], data: { items: d.items } },
    ], completion: { type: 'required-blocks', blockRefs: [check] } };
}

export const batchBPart3: Part = { id: 'harmony.part.keys', title: 'PART 3. 조성과 조표', lessons: [
  makeLesson({ key: 'lesson.major-key', legacy: '3-1', title: '장조', summary: '장음계의 간격 구조로 장조의 밝고 안정적인 중심을 확인합니다.', objective: '주어진 으뜸음에서 장음계의 온·반음 구조를 설명한다.', prerequisiteRefs: ['harmony.lesson.consonance.lesson'], markdown: '장조는 장음계를 중심으로 형성되는 조성입니다. 장음계의 간격은 **온–온–반–온–온–온–반**이며, 첫 음인 으뜸음이 조성의 중심을 만듭니다.', groups: [[C4], [D4], [E4], [F4], [G4], [A4], [B4], [C5]], activityTitle: 'C장음계의 간격 듣기', prompt: '장음계의 3–4음과 7–8음 사이는 무엇인가요?', options: [{ id: 'half', label: '반음' }, { id: 'whole', label: '온음' }, { id: 'third', label: '3도' }], answer: 'half', explanation: '장음계 구조에서 3–4음과 7–8음 사이는 반음입니다.', items: ['장조는 장음계를 중심으로 합니다.', '장음계 구조는 온–온–반–온–온–온–반입니다.', '으뜸음은 조성의 중심입니다.'] }),
  makeLesson({ key: 'lesson.minor-key', legacy: '3-2', title: '단조', summary: '자연·화성·가락단음계의 6음과 7음 변화를 비교합니다.', objective: '세 가지 단음계의 6음과 7음 차이를 구별한다.', prerequisiteRefs: ['harmony.lesson.major-key.lesson'], markdown: '단조는 단음계를 중심으로 합니다. **자연단음계**를 기본으로, 화성단음계는 7음을 올려 이끎음을 만들고 가락단음계는 올라갈 때 6·7음을 올리는 관습을 사용합니다.', groups: [[A4], [B4], [C5], [D5], [E5], [F5], [Gs5], [A5]], activityTitle: 'A화성단음계 듣기', prompt: 'A화성단음계에서 올라가는 음은 무엇인가요?', options: [{ id: 'seventh', label: '7음 G가 G♯으로 올라간다' }, { id: 'third', label: '3음 C가 C♯으로 올라간다' }, { id: 'none', label: '아무 음도 변하지 않는다' }], answer: 'seventh', explanation: '화성단음계는 7음을 반음 올려 으뜸음으로 향하는 이끎음을 만듭니다.', items: ['자연단음계는 기본 형태입니다.', '화성단음계는 7음을 올립니다.', '가락단음계는 선율 방향에 따라 6·7음이 달라질 수 있습니다.'] }),
  makeLesson({ key: 'lesson.key-signature', legacy: '3-3', title: '조표', summary: '반복되는 변화표를 조표로 묶어 조성 후보를 찾습니다.', objective: '조표의 샵·플랫 수에서 대표 장조를 찾는다.', prerequisiteRefs: ['harmony.lesson.minor-key.lesson'], markdown: '조표는 곡 전체에 반복 적용되는 샵 또는 플랫입니다. 장·단음계의 구조를 매번 적지 않고 표시하며, 같은 조표를 공유하는 장조와 단조가 있을 수 있습니다.', groups: [[G4], [A4], [B4], [C5], [D5], [E5], [Fs5], [G5]], activityTitle: 'F♯이 포함된 G장음계 듣기', prompt: '샵 한 개(F♯)인 대표 장조는 무엇인가요?', options: [{ id: 'g', label: 'G장조' }, { id: 'c', label: 'C장조' }, { id: 'f', label: 'F장조' }], answer: 'g', explanation: 'G장조는 F♯ 한 개를 조표로 사용합니다.', items: ['조표는 반복되는 변화표를 묶어 표시합니다.', '샵 한 개의 대표 장조는 G장조입니다.', '같은 조표를 공유하는 장조와 단조가 있습니다.'] }),
  makeLesson({ key: 'lesson.circle-of-fifths', legacy: '3-4', title: 'Circle of Fifths', summary: '5도 이동으로 가까운 조성과 조표의 변화를 연결합니다.', objective: '5도권에서 이동 방향과 샵·플랫 증가를 연결한다.', prerequisiteRefs: ['harmony.lesson.key-signature.lesson'], markdown: '5도권은 조성 사이의 관계를 시각화한 구조입니다. C에서 완전5도씩 시계방향으로 이동하면 G–D–A로 이어지며 샵이 하나씩 늘어납니다. 반대방향에서는 플랫이 하나씩 늘어납니다.', groups: [[C4], [G4], [D5], [A5]], activityTitle: 'C–G–D–A의 5도 이동 듣기', prompt: '5도권에서 C에서 시계방향으로 한 칸 이동하면 어떤 조인가요?', options: [{ id: 'g', label: 'G장조' }, { id: 'f', label: 'F장조' }, { id: 'a', label: 'A단조' }], answer: 'g', explanation: 'C에서 완전5도 위는 G이며 샵이 한 개 늘어납니다.', items: ['시계방향은 완전5도 위로 이동합니다.', '시계방향으로 갈수록 샵이 늘어납니다.', '가까운 조성은 공통음이 많습니다.'] }),
  makeLesson({ key: 'lesson.related-keys', legacy: '3-5', title: '관계조', summary: '나란한조·같은으뜸조·딸림조의 차이를 확인합니다.', objective: '주어진 장조의 나란한단조와 같은으뜸단조를 구별한다.', prerequisiteRefs: ['harmony.lesson.circle-of-fifths.lesson'], markdown: '**나란한조**는 같은 조표를 공유하고, **같은으뜸조**는 으뜸음이 같습니다. 딸림조와 버금딸림조는 으뜸음에서 각각 5도 위와 5도 아래의 관계입니다.', groups: [[C4, E4, G4], [A3, C4, E4], [G3, B3, D4]], activityTitle: 'C장조·A단조·G장조의 중심 화음 비교', prompt: 'C장조의 나란한단조는 무엇인가요?', options: [{ id: 'a-minor', label: 'A단조' }, { id: 'c-minor', label: 'C단조' }, { id: 'g-minor', label: 'G단조' }], answer: 'a-minor', explanation: 'C장조와 A단조는 조표가 없는 나란한조입니다.', items: ['나란한조는 조표가 같습니다.', '같은으뜸조는 으뜸음이 같습니다.', '관계조는 전조와 차용화음의 기초입니다.'] }),
] };

export const batchBPart4Before: Lesson[] = [makeLesson({ key: 'lesson.chord-definition', legacy: '4-1', title: '화음의 정의', summary: '여러 음이 동시에 울려 하나의 화성 단위를 만드는 원리를 살펴봅니다.', objective: '근음 위에 3도씩 쌓아 3화음을 구성하는 원리를 설명한다.', prerequisiteRefs: ['harmony.lesson.related-keys.lesson'], markdown: '화음은 둘 이상의 음이 동시에 울려 하나의 화성적 단위를 이루는 것입니다. 전통 화성학에서는 근음 위에 **3도씩 쌓은 화음**을 기본으로 다룹니다.', groups: [[C4, E4, G4]], activityTitle: 'C–E–G 화음 듣기', prompt: 'C에서 3도씩 두 번 쌓은 기본 3화음은 무엇인가요?', options: [{ id: 'ceg', label: 'C–E–G' }, { id: 'cdf', label: 'C–D–F' }, { id: 'cfg', label: 'C–F–G' }], answer: 'ceg', explanation: 'C에서 3도 위 E, 다시 3도 위 G를 쌓습니다.', items: ['화음은 동시에 울리는 음의 단위입니다.', '전통 화성학은 3도 쌓기를 기본으로 합니다.', '가장 아래 음과 근음은 자리바꿈에서 달라질 수 있습니다.'] })];

export const batchBPart4After: Lesson[] = [
  makeLesson({ key: 'lesson.triad-inversion', legacy: '4-3', title: '자리바꿈', summary: '베이스음에 따라 기본형·제1전위·제2전위를 구별합니다.', objective: '3화음의 최저음에서 자리바꿈 형태를 판별한다.', prerequisiteRefs: ['harmony.lesson.triad'], markdown: '화음의 최저음이 근음이면 **기본형**, 3음이면 **제1전위**, 5음이면 **제2전위**입니다. 자리바꿈은 구성음과 기능을 유지하면서 베이스 진행과 울림을 바꿉니다.', groups: [[C4, E4, G4], [E4, G4, C5], [G3, C4, E4]], activityTitle: 'C장3화음의 세 배치 비교', prompt: 'C장3화음에서 E가 최저음이면 어떤 형태인가요?', options: [{ id: 'first', label: '제1전위' }, { id: 'root', label: '기본형' }, { id: 'second', label: '제2전위' }], answer: 'first', explanation: '3음 E가 베이스이므로 제1전위입니다.', items: ['근음이 베이스면 기본형입니다.', '3음이 베이스면 제1전위입니다.', '5음이 베이스면 제2전위입니다.'] }),
  makeLesson({ key: 'lesson.chord-symbols', legacy: '4-4', title: '코드 표기법', summary: '문자 코드와 로마숫자가 보여주는 정보를 구별합니다.', objective: '문자 코드와 로마숫자 표기의 역할을 구별한다.', prerequisiteRefs: ['harmony.lesson.triad-inversion.lesson'], markdown: '문자 기호는 **실제 코드 이름과 성질**을, 로마숫자는 **조성 안에서의 음계 위치와 기능**을 보여줍니다. 같은 C화음도 C장조에서는 I, G장조에서는 IV가 됩니다.', groups: [[C4, E4, G4], [A3, C4, E4], [G3, B3, D4, F4]], activityTitle: 'C·Am·G7 구성음 비교', prompt: 'C장조에서 C장3화음의 로마숫자는 무엇인가요?', options: [{ id: 'one', label: 'I' }, { id: 'four', label: 'IV' }, { id: 'five', label: 'V' }], answer: 'one', explanation: 'C는 C장조의 첫 음을 근음으로 하는 으뜸화음이므로 I입니다.', items: ['문자 코드는 실제 근음과 성질을 표시합니다.', '로마숫자는 조성 안의 위치를 표시합니다.', '로마숫자 해석에는 조성 문맥이 필요합니다.'] }),
];

export const batchBPart5: Part = { id: 'harmony.part.seventh-chords', title: 'PART 5. 7화음', lessons: [
  makeLesson({ key: 'lesson.seventh-concept', legacy: '5-1', title: '7화음의 개념', summary: '3화음 위에 7음을 더해 네 음의 화음을 만듭니다.', objective: '3화음에 3도를 한 번 더 쌓아 7화음을 구성한다.', prerequisiteRefs: ['harmony.lesson.chord-symbols.lesson'], markdown: '7화음은 3화음 위에 다시 3도를 쌓아 **근음·3음·5음·7음**의 네 음으로 만듭니다. 7음이 더해지면서 긴장과 진행 방향이 뚜렷해집니다.', groups: [[G3, B3, D4, F4]], activityTitle: 'G7의 네 구성음 듣기', prompt: '7화음은 기본적으로 몇 개의 음으로 이루어지나요?', options: [{ id: 'four', label: '4개' }, { id: 'three', label: '3개' }, { id: 'five', label: '5개' }], answer: 'four', explanation: '3화음에 7음을 더해 네 개의 음으로 구성합니다.', items: ['7화음은 네 구성음을 가집니다.', '3화음 위에 3도를 한 번 더 쌓습니다.', '7음은 긴장과 해결 방향을 강화합니다.'] }),
  makeLesson({ key: 'lesson.seventh-types', legacy: '5-2', title: '7화음의 종류', summary: '3화음의 성질과 7도의 조합으로 주요 7화음을 구별합니다.', objective: '구성음에서 장7·단7·도미넌트7 화음을 구별한다.', prerequisiteRefs: ['harmony.lesson.seventh-concept.lesson'], markdown: '대표적인 7화음에는 장7, 단7, 도미넌트7, 반감7, 감7이 있습니다. 아래 3화음의 성질과 근음에서 7음까지의 거리를 함께 봅니다.', groups: [[C4, E4, G4, B4], [C4, Eb4, G4, Bb4], [C4, E4, G4, Bb4]], activityTitle: 'Cmaj7·Cm7·C7 비교', prompt: 'C–E–G–B♭의 화음 종류는 무엇인가요?', options: [{ id: 'dominant', label: '도미넌트7(C7)' }, { id: 'major', label: '장7(Cmaj7)' }, { id: 'minor', label: '단7(Cm7)' }], answer: 'dominant', explanation: '장3화음 C–E–G에 단7도 B♭이 더해진 도미넌트7화음입니다.', items: ['장7화음은 장3화음과 장7도의 결합입니다.', '단7화음은 단3화음과 단7도의 결합입니다.', '도미넌트7화음은 장3화음과 단7도의 결합입니다.'] }),
  makeLesson({ key: 'lesson.seventh-inversion', legacy: '5-3', title: '7화음의 전위', summary: '최저음에 따라 세 가지 7화음 전위를 구별합니다.', objective: '7화음의 베이스음에서 기본형과 세 전위를 판별한다.', prerequisiteRefs: ['harmony.lesson.seventh-types.lesson'], markdown: '7화음은 구성음이 네 개이므로 세 번 전위할 수 있습니다. 3음·5음·7음이 베이스일 때 각각 **제1·2·3전위**입니다.', groups: [[B3, D4, F4, G4], [D4, F4, G4, B4], [F3, G3, B3, D4]], activityTitle: 'G7의 세 전위 비교', prompt: 'G7에서 7음 F가 베이스이면 어떤 형태인가요?', options: [{ id: 'third', label: '제3전위' }, { id: 'first', label: '제1전위' }, { id: 'second', label: '제2전위' }], answer: 'third', explanation: '화음의 7음이 베이스이면 제3전위입니다.', items: ['7화음에는 세 가지 전위가 있습니다.', '3음·5음·7음 베이스가 제1·2·3전위입니다.', '전위는 베이스 진행과 해결에 영향을 줍니다.'] }),
  makeLesson({ key: 'lesson.seventh-resolution', legacy: '5-4', title: '해결 원리', summary: '화음의 7음과 이끎음이 향하는 기본 방향을 확인합니다.', objective: '도미넌트7화음의 7음과 이끎음의 기본 해결 방향을 설명한다.', prerequisiteRefs: ['harmony.lesson.seventh-inversion.lesson'], markdown: '7화음의 불협화음정은 일정한 방향으로 해결되는 경향이 있습니다. V7의 **화음 7음은 한 음 아래로**, **이끎음은 으뜸음으로 위로** 진행하는 것이 기본입니다.', groups: [[G3, B3, D4, F4], [C4, E4, G4]], activityTitle: 'G7에서 C화음으로 해결 듣기', playbackMode: 'progression', prompt: 'C장조의 G7에서 F와 B는 각각 어디로 해결되는 것이 기본인가요?', options: [{ id: 'resolve', label: 'F→E, B→C' }, { id: 'opposite', label: 'F→G, B→A' }, { id: 'stay', label: '둘 다 그대로 유지' }], answer: 'resolve', explanation: '화음의 7음 F는 E로 내려가고 이끎음 B는 C로 올라갑니다.', items: ['화음의 7음은 보통 아래로 해결됩니다.', '이끎음은 으뜸음으로 올라갑니다.', '실제 성부배치에서는 중복과 문맥도 함께 봅니다.'] }),
] };
