import { blockVersion, type Lesson, type Part } from '@interactive-textbook/schema';
import type { Pitch } from '@interactive-textbook/subject-music';

const p=(step:Pitch['step'],octave:number,alter:Pitch['alter']=0):Pitch=>({step,alter,octave});
const C4=p('C',4),Cs4=p('C',4,1),D4=p('D',4),E4=p('E',4),F4=p('F',4),Fs4=p('F',4,1),G4=p('G',4),Gs4=p('G',4,1),Ab4=p('A',4,-1),A4=p('A',4),As4=p('A',4,1),Bb4=p('B',4,-1),B4=p('B',4),C5=p('C',5),Cs5=p('C',5,1),Db5=p('D',5,-1),D5=p('D',5),E5=p('E',5),F5=p('F',5),Fs5=p('F',5,1),G5=p('G',5);
const opts=(...labels:string[])=>labels.map((label,index)=>({id:`o${index+1}`,label}));
interface Draft{key:string;legacy:string;title:string;summary:string;objective:string;markdown:string;groups:Pitch[][];activityTitle:string;prompt:string;options:Array<{id:string;label:string}>;answer:string;explanation:string;items:string[];prerequisiteRefs?:string[];}
function lesson(d:Draft):Lesson{const prefix=`harmony.${d.key}`,objective=`${prefix}.objective`,data=`${prefix}.data.examples`,check=`${prefix}.block.check`;return{id:`${prefix}.lesson`,title:`${d.legacy}. ${d.title}`,summary:d.summary,estimatedMinutes:12,prerequisiteRefs:d.prerequisiteRefs,objectives:[{id:objective,title:d.objective}],data:[{id:data,subject:'music',kind:'pitch-groups',value:d.groups}],blocks:[{id:`${prefix}.block.concept`,blockVersion,type:'content.markdown',objectiveRefs:[objective],data:{markdown:d.markdown}},{id:`${prefix}.block.examples`,blockVersion,type:'activity.subject',objectiveRefs:[objective],dataRefs:[data],data:{subject:'music',tool:'pitch-pair-viewer',title:d.activityTitle,input:{pairs:d.groups,interactive:false}}},{id:check,blockVersion,type:'assessment.multiple-choice',objectiveRefs:[objective],data:{prompt:d.prompt,options:d.options,answer:d.answer,explanation:d.explanation}},{id:`${prefix}.block.summary`,blockVersion,type:'content.summary',objectiveRefs:[objective],data:{items:d.items}}],completion:{type:'required-blocks',blockRefs:[check]}};}

export const batchDPart10:Part={id:'harmony.part.nonchord-tones',title:'PART 10. 비화성음',lessons:[
lesson({key:'lesson.passing-tone',legacy:'10-1',title:'경과음',summary:'두 화음음 사이를 순차로 연결하는 비화성음을 찾습니다.',objective:'순차 진입·순차 이탈하는 경과음을 식별한다.',prerequisiteRefs:['harmony.lesson.common-progressions.lesson'],markdown:'**경과음**은 서로 다른 두 화음음 사이를 같은 방향의 순차 진행으로 연결합니다. C–D–E에서 D가 현재 화음에 속하지 않으면 경과음입니다.',groups:[[C4,D4,E4],[E4,F4,G4]],activityTitle:'순차로 사이를 잇는 경과음',prompt:'C–D–E에서 가운데 D가 비화성음이면 종류는?',options:opts('경과음','보조음','계류음'),answer:'o1',explanation:'D는 C와 E 사이를 같은 방향으로 순차 연결합니다.',items:['경과음은 순차로 들어오고 순차로 나갑니다.','진행 방향이 유지됩니다.','앞뒤 화음음을 먼저 확인합니다.']}),
lesson({key:'lesson.neighbor-tone',legacy:'10-2',title:'보조음',summary:'한 화음음에서 이웃음으로 갔다가 돌아오는 움직임을 봅니다.',objective:'원래 음으로 복귀하는 보조음을 식별한다.',prerequisiteRefs:['harmony.lesson.passing-tone.lesson'],markdown:'**보조음**은 화음음에서 2도 위나 아래로 움직였다가 같은 화음음으로 돌아옵니다. C–D–C에서 D가 보조음입니다.',groups:[[C4,D4,C4],[E4,D4,E4]],activityTitle:'위·아래 보조음 비교',prompt:'E–D–E의 가운데 D가 비화성음이면?',options:opts('보조음','경과음','선행음'),answer:'o1',explanation:'이웃음 D로 갔다가 출발음 E로 돌아옵니다.',items:['보조음은 순차로 벗어납니다.','같은 음으로 순차 복귀합니다.','위보조음과 아래보조음이 있습니다.']}),
lesson({key:'lesson.suspension',legacy:'10-3',title:'계류음',summary:'이전 화음음을 유지해 불협을 만들고 아래로 해결합니다.',objective:'준비·계류·해결의 세 단계를 설명한다.',prerequisiteRefs:['harmony.lesson.neighbor-tone.lesson'],markdown:'**계류음**은 앞 화음의 음이 다음 화음까지 유지되어 불협을 만든 뒤 보통 아래로 순차 해결됩니다. 준비–계류–해결을 함께 확인해야 합니다.',groups:[[G4,G4,Fs4],[C5,C5,B4]],activityTitle:'유지된 음의 아래 해결',prompt:'계류음의 일반적인 해결 방향은?',options:opts('아래로 순차 진행','위로 도약','그대로 유지'),answer:'o1',explanation:'전통적인 계류음은 준비된 음이 유지된 뒤 아래로 순차 해결됩니다.',items:['앞 화음에서 준비됩니다.','다음 화음까지 같은 높이로 유지됩니다.','보통 아래로 순차 해결됩니다.']}),
lesson({key:'lesson.appoggiatura',legacy:'10-4',title:'선행음',summary:'다음 화음의 구성음이 화음 변화보다 먼저 나타나는 움직임을 듣습니다.',objective:'다음 화음음을 미리 제시하는 선행음을 계류음과 구별한다.',prerequisiteRefs:['harmony.lesson.suspension.lesson'],markdown:'이 교재에서 **선행음(anticipation)**은 다음 화음의 구성음이 화음 변화보다 먼저 나타나는 비화성음입니다. 이전 화음의 음을 다음 화음까지 유지하는 계류음과 시간 방향이 반대입니다.',groups:[[E4,G4,C5],[G4,B4,C5]],activityTitle:'다음 화음음을 미리 제시하기',prompt:'선행음이 미리 들려주는 것은?',options:opts('다음 화음의 구성음','이전 화음의 근음','조표의 변화'),answer:'o1',explanation:'새 화음의 구성음이 실제 화음 변화보다 먼저 나타납니다.',items:['다음 화음의 음을 미리 제시합니다.','계류음은 이전 화음의 음을 유지합니다.','두 비화성음은 시간 방향이 반대입니다.']}),
lesson({key:'lesson.escape-tone',legacy:'10-5',title:'이탈음',summary:'순차 진입한 비화성음이 반대 방향으로 도약해 나갑니다.',objective:'순차 진입·반대 방향 도약 이탈을 식별한다.',prerequisiteRefs:['harmony.lesson.appoggiatura.lesson'],markdown:'**이탈음**은 화음음에서 순차로 비화성음에 들어간 뒤, 반대 방향으로 도약하여 다음 화음음으로 갑니다.',groups:[[C4,D4,A4],[E4,F4,C4]],activityTitle:'순차 진입 후 반대 도약',prompt:'C–D–A에서 D가 비화성음이고 반대 방향으로 도약한다면?',options:opts('이탈음','계류음','경과음'),answer:'o1',explanation:'D로 순차 진입한 뒤 A로 반대 방향 도약해 이탈합니다.',items:['순차로 들어옵니다.','반대 방향으로 도약합니다.','선행음과 진입·이탈 방식이 반대입니다.']}),
lesson({key:'lesson.cambiata',legacy:'10-6',title:'도약진행음',summary:'비화성음 주변의 도약과 순차 진행 패턴을 구별합니다.',objective:'도약진행음의 진입·이탈 패턴을 다른 비화성음과 비교한다.',prerequisiteRefs:['harmony.lesson.escape-tone.lesson'],markdown:'**도약진행음(cambiata)**은 문맥과 시대에 따라 정의가 다를 수 있으나, 전형적으로 순차 진행과 3도 도약이 결합된 장식 패턴입니다. 개별 음보다 전체 선율을 봅니다.',groups:[[E4,D4,B4,C5],[C5,B4,G4,A4]],activityTitle:'순차와 3도 도약의 결합',prompt:'도약진행음을 판별할 때 가장 중요한 것은?',options:opts('앞뒤 선율 전체','비화성음 한 음만','코드 이름만'),answer:'o1',explanation:'진입과 이탈의 방향·간격을 포함한 전체 패턴을 확인해야 합니다.',items:['순차와 도약이 결합됩니다.','앞뒤 음의 방향과 간격을 봅니다.','시대·교재에 따른 정의 차이를 주의합니다.']})]};

export const batchDPart11:Part={id:'harmony.part.applied-chords',title:'PART 11. 적용화음',lessons:[
lesson({key:'lesson.secondary-dominant',legacy:'11-1',title:'부속도미넌트',summary:'다이어토닉 화음을 잠시 으뜸처럼 강조하는 V/x를 확인합니다.',objective:'목표 화음의 도미넌트를 계산하고 V/x로 분석한다.',prerequisiteRefs:['harmony.lesson.cambiata.lesson'],markdown:'**부속도미넌트**는 으뜸화음 이외의 다이어토닉 화음을 잠시 목표로 삼는 도미넌트입니다. C장조에서 A7–Dm은 Dm(ii)의 도미넌트이므로 V/ii–ii입니다.',groups:[[A4,Cs5,E5,G5],[D4,F4,A4]],activityTitle:'V/ii에서 ii로 해결',prompt:'C장조에서 A7이 Dm으로 해결되면 A7의 분석은?',options:opts('V/ii','V/V','V/IV'),answer:'o1',explanation:'A는 D의 완전5도 위이므로 A7은 ii(Dm)의 도미넌트입니다.',items:['목표 화음을 먼저 찾습니다.','목표 근음의 5도 위에 V를 만듭니다.','슬래시 뒤에는 목표 화음의 로마숫자를 씁니다.']}),
lesson({key:'lesson.secondary-leading-tone',legacy:'11-2',title:'부속 Leading Tone',summary:'목표 화음 바로 아래의 이끎음 감화음을 찾습니다.',objective:'vii°/x의 구성음과 반음 해결을 설명한다.',prerequisiteRefs:['harmony.lesson.secondary-dominant.lesson'],markdown:'**부속 이끎음화음**은 목표 화음의 근음 바로 아래 반음에서 시작하는 감화음입니다. C장조에서 C♯–E–G가 Dm으로 가면 vii°/ii입니다.',groups:[[Cs4,E4,G4],[D4,F4,A4]],activityTitle:'vii°/ii에서 ii로',prompt:'C♯–E–G가 Dm으로 해결될 때 분석은?',options:opts('vii°/ii','vii°/V','ii°'),answer:'o1',explanation:'C♯은 목표 D의 이끎음이므로 Dm(ii)에 대한 vii°입니다.',items:['목표 근음 아래 반음을 찾습니다.','그 음 위에 감화음을 만듭니다.','이끎음은 목표 근음으로 올라갑니다.']}),
lesson({key:'lesson.applied-chord',legacy:'11-3',title:'적용화음',summary:'부속도미넌트와 부속 이끎음화음을 한 체계로 분석합니다.',objective:'적용화음과 실제 전조를 지속성으로 구별한다.',prerequisiteRefs:['harmony.lesson.secondary-leading-tone.lesson'],markdown:'**적용화음**은 V/x와 vii°/x를 포함하며 목표 화음을 일시적으로 으뜸화합니다. 목표 조성이 계속 확립되면 적용화음이 아니라 전조로 해석할 수 있습니다.',groups:[[E4,Gs4,B4,D5],[A4,C5,E5],[D4,Fs4,A4,C5],[G4,B4,D5]],activityTitle:'V/vi–vi와 V/V–V',prompt:'적용화음과 전조를 구별하는 핵심 단서는?',options:opts('새 조성의 지속과 확립','변화표 하나의 존재','화음의 음 개수'),answer:'o1',explanation:'짧은 으뜸화인지 새 조성이 지속적으로 확립되는지 문맥을 봅니다.',items:['적용화음은 일시적 강조입니다.','V/x와 vii°/x가 대표적입니다.','지속적 조성 확립은 전조 가능성을 높입니다.']})]};

export const batchDPart12:Part={id:'harmony.part.chromatic-harmony',title:'PART 12. 반음계 화성',lessons:[
lesson({key:'lesson.modal-interchange',legacy:'12-1',title:'Modal Interchange',summary:'같은으뜸조에서 화음을 빌려 색채를 바꿉니다.',objective:'장조에서 같은으뜸단조의 차용화음을 식별한다.',prerequisiteRefs:['harmony.lesson.applied-chord.lesson'],markdown:'**Modal Interchange(차용화음)**는 같은 으뜸음을 가진 다른 선법에서 화음을 빌립니다. C장조의 iv(F–A♭–C)는 C단조에서 빌린 대표 화음입니다.',groups:[[F4,A4,C5],[F4,Ab4,C5],[Bb4,D5,F5]],activityTitle:'IV와 차용 iv 비교',prompt:'C장조에서 F–A♭–C는 보통 무엇으로 분석하나요?',options:opts('차용 iv','다이어토닉 IV','V/V'),answer:'o1',explanation:'A♭이 포함된 F단3화음은 같은으뜸단조 C단조에서 빌린 iv입니다.',items:['같은으뜸조·선법에서 빌립니다.','변화음의 출처를 확인합니다.','iv, ♭VI, ♭VII 등이 자주 쓰입니다.']}),
lesson({key:'lesson.neapolitan-sixth',legacy:'12-2',title:'Neapolitan Sixth',summary:'낮춘 2음 위의 장3화음이 제1전위로 Dominant를 준비합니다.',objective:'N6의 음계 위치·전위·기능을 설명한다.',prerequisiteRefs:['harmony.lesson.modal-interchange.lesson'],markdown:'**나폴리6화음(N6)**은 낮춘 2음(♭II) 위의 장3화음을 주로 제1전위로 사용합니다. 단조에서 흔하며 Subdominant 기능으로 V를 준비합니다.',groups:[[F4,Ab4,Db5],[G4,B4,D5]],activityTitle:'C단조 N6에서 V로',prompt:'C단조의 N6 구성음은?',options:opts('F–A♭–D♭','D–F–A♭','G–B–D'),answer:'o1',explanation:'♭II인 D♭ 장3화음의 제1전위이므로 F–A♭–D♭입니다.',items:['근음은 낮춘 2음입니다.','보통 제1전위로 씁니다.','S 기능으로 V를 준비합니다.']}),
lesson({key:'lesson.augmented-sixth',legacy:'12-3',title:'증6화음',summary:'♭6과 ♯4가 바깥으로 벌어져 V의 근음으로 해결됩니다.',objective:'증6도 핵심음의 V 해결 방향을 설명한다.',prerequisiteRefs:['harmony.lesson.neapolitan-sixth.lesson'],markdown:'**증6화음**의 핵심은 ♭6과 ♯4입니다. 두 음은 증6도를 이루고 바깥 방향으로 벌어져 둘 다 Dominant의 근음 5음으로 해결됩니다.',groups:[[Ab4,C5,Fs5],[G4,B4,D5]],activityTitle:'A♭–F♯에서 G로 해결',prompt:'C조에서 증6도의 A♭과 F♯은 어디로 해결되나요?',options:opts('둘 다 G','둘 다 C','A와 F'),answer:'o1',explanation:'A♭은 내려가고 F♯은 올라가 Dominant 근음 G에 도착합니다.',items:['핵심음은 ♭6과 ♯4입니다.','바깥 방향으로 V 근음에 해결됩니다.','이탈리아·프랑스·독일형이 있습니다.']})]};

export const batchDPart13:Part={id:'harmony.part.modulation',title:'PART 13. 전조',lessons:[
lesson({key:'lesson.modulation-concept',legacy:'13-1',title:'전조의 개념',summary:'한 조성 중심에서 다른 조성 중심으로 이동하는 과정을 봅니다.',objective:'일시적 으뜸화와 확립된 전조를 구별한다.',prerequisiteRefs:['harmony.lesson.augmented-sixth.lesson'],markdown:'**전조**는 조성의 중심이 새로운 으뜸음으로 이동하는 것입니다. 변화화음 하나만으로 결정하지 않고 새 조성의 Dominant–Tonic, 지속 시간, 종지로 확립 여부를 판단합니다.',groups:[[C4,E4,G4],[D4,Fs4,A4],[G4,B4,D5]],activityTitle:'C장조에서 G장조 중심으로',prompt:'전조를 가장 강하게 확인하는 단서는?',options:opts('새 조성의 V–I와 종지','우연한 변화표 하나','같은 코드의 반복'),answer:'o1',explanation:'새 조성의 기능 진행과 종지는 중심 이동을 확립합니다.',items:['새로운 으뜸 중심이 생깁니다.','기능 진행과 종지를 함께 봅니다.','짧은 강조는 으뜸화일 수 있습니다.']}),
lesson({key:'lesson.pivot-chord-modulation',legacy:'13-2',title:'공통화음 전조',summary:'두 조성에서 모두 해석되는 화음을 경첩으로 사용합니다.',objective:'공통화음의 두 로마숫자 기능을 분석한다.',prerequisiteRefs:['harmony.lesson.modulation-concept.lesson'],markdown:'**공통화음 전조**는 출발 조와 도착 조에 모두 속하는 화음을 피벗으로 사용합니다. C장조의 Am은 vi이면서 G장조의 ii가 될 수 있습니다.',groups:[[C4,E4,G4],[A4,C5,E5],[D4,Fs4,A4],[G4,B4,D5]],activityTitle:'C의 vi = G의 ii',prompt:'C장조에서 G장조로 갈 때 Am의 두 분석은?',options:opts('C: vi, G: ii','C: IV, G: V','C: ii, G: vi'),answer:'o1',explanation:'Am은 C장조의 vi이자 G장조의 ii입니다.',items:['두 조성에 공통인 화음을 찾습니다.','피벗 전후 기능이 달라집니다.','도착 조의 종지로 전조를 확립합니다.']}),
lesson({key:'lesson.common-tone-modulation',legacy:'13-3',title:'공통음 전조',summary:'한 음을 유지해 먼 조성 사이의 연결고리를 만듭니다.',objective:'유지되는 공통음과 전후 화음의 역할을 설명한다.',prerequisiteRefs:['harmony.lesson.pivot-chord-modulation.lesson'],markdown:'**공통음 전조**는 두 조성 또는 화음이 공유하는 한 음을 유지하거나 강조해 연결합니다. 공통화음이 부족한 먼 조성에서도 부드러운 청각적 다리를 만듭니다.',groups:[[C4,E4,G4],[Cs4,E4,Gs4],[A4,Cs5,E5]],activityTitle:'E 공통음으로 새로운 중심 연결',prompt:'공통음 전조의 핵심 연결 요소는?',options:opts('전후에 유지되는 한 음','동일한 조표','동일한 베이스'),answer:'o1',explanation:'공유되는 음이 두 화성 영역을 청각적으로 이어 줍니다.',items:['전후 화음의 공통음을 찾습니다.','공통음을 유지하거나 강조합니다.','새 조성의 기능 진행으로 도착을 확인합니다.']}),
lesson({key:'lesson.direct-modulation',legacy:'13-4',title:'직접 전조',summary:'피벗 없이 새로운 조성으로 즉시 전환하는 효과를 듣습니다.',objective:'직접 전조의 경계와 새 조성 확립을 식별한다.',prerequisiteRefs:['harmony.lesson.common-tone-modulation.lesson'],markdown:'**직접 전조**는 공통화음 없이 구절 경계 등에서 바로 새 조성으로 이동합니다. 대비 효과가 크며 새 조의 선율·화음·종지가 곧바로 중심을 확립합니다.',groups:[[C4,E4,G4],[Cs4,F4,Gs4],[Fs4,As4,Cs5]],activityTitle:'C장조에서 F♯장조로 직접 전환',prompt:'직접 전조의 특징은?',options:opts('피벗 없이 새 조로 전환','공통화음을 반드시 사용','같은 조성 안에서만 진행'),answer:'o1',explanation:'피벗 과정 없이 경계에서 새로운 조성을 바로 제시합니다.',items:['공통화음이 필수는 아닙니다.','구절 경계에서 자주 나타납니다.','새 조성의 확립 단서를 확인합니다.']}),
lesson({key:'lesson.chromatic-modulation',legacy:'13-5',title:'반음계적 전조',summary:'한 성부의 반음 이동이 화음의 기능과 조성을 바꿉니다.',objective:'반음계적 성부 변화가 새 조성 기능을 만드는 과정을 설명한다.',prerequisiteRefs:['harmony.lesson.direct-modulation.lesson'],markdown:'**반음계적 전조**는 한두 성부가 반음으로 움직이며 기존 화음이 새 조성의 기능화음으로 변형됩니다. 음의 철자와 해결 방향이 새 중심을 드러냅니다.',groups:[[C4,E4,G4],[C4,E4,Gs4],[Cs4,E4,Gs4]],activityTitle:'G–G♯과 C–C♯의 반음 변화',prompt:'반음계적 전조를 분석할 때 특히 중요한 것은?',options:opts('변화음의 철자와 해결 방향','음량만','악기의 종류'),answer:'o1',explanation:'어떤 음이 어떻게 변해 어느 기능으로 해결되는지가 새 조성을 보여줍니다.',items:['성부가 반음계적으로 변합니다.','변화음의 철자를 정확히 봅니다.','새 조성의 기능과 종지로 해석을 확인합니다.']})]};
