import { blockVersion, type Lesson, type Part } from '@interactive-textbook/schema';
import type { Pitch } from '@interactive-textbook/subject-music';

const p=(step:Pitch['step'],octave:number,alter:Pitch['alter']=0):Pitch=>({step,alter,octave});
const C3=p('C',3),G3=p('G',3),A3=p('A',3),B3=p('B',3),C4=p('C',4),D4=p('D',4),Ds4=p('D',4,1),E4=p('E',4),F4=p('F',4),Fs4=p('F',4,1),G4=p('G',4),Gs4=p('G',4,1),A4=p('A',4),Bb4=p('B',4,-1),B4=p('B',4),C5=p('C',5),D5=p('D',5),E5=p('E',5),F5=p('F',5),G5=p('G',5);
const I=[C4,E4,G4],ii=[D4,F4,A4],IV=[F4,A4,C5],V=[G3,B3,D4],vi=[A3,C4,E4];
const opts=(...labels:string[])=>labels.map((label,index)=>({id:`o${index+1}`,label}));
interface Draft{key:string;legacy:string;title:string;summary:string;objective:string;markdown:string;groups:Pitch[][];activityTitle:string;prompt:string;options:Array<{id:string;label:string}>;answer:string;explanation:string;items:string[];prerequisiteRefs?:string[];}
function lesson(d:Draft):Lesson{const prefix=`harmony.${d.key}`,objective=`${prefix}.objective`,data=`${prefix}.data.examples`,check=`${prefix}.block.check`;return{id:`${prefix}.lesson`,title:`${d.legacy}. ${d.title}`,summary:d.summary,estimatedMinutes:12,prerequisiteRefs:d.prerequisiteRefs,objectives:[{id:objective,title:d.objective}],data:[{id:data,subject:'music',kind:'pitch-groups',value:d.groups}],blocks:[{id:`${prefix}.block.concept`,blockVersion,type:'content.markdown',objectiveRefs:[objective],data:{markdown:d.markdown}},{id:`${prefix}.block.examples`,blockVersion,type:'activity.subject',objectiveRefs:[objective],dataRefs:[data],data:{subject:'music',tool:'pitch-pair-viewer',title:d.activityTitle,input:{pairs:d.groups,interactive:false}}},{id:check,blockVersion,type:'assessment.multiple-choice',objectiveRefs:[objective],data:{prompt:d.prompt,options:d.options,answer:d.answer,explanation:d.explanation}},{id:`${prefix}.block.summary`,blockVersion,type:'content.summary',objectiveRefs:[objective],data:{items:d.items}}],completion:{type:'required-blocks',blockRefs:[check]}};}

export const batchEPart14:Part={id:'harmony.part.analysis',title:'PART 14. 화성 분석',lessons:[
lesson({key:'lesson.advanced-roman-analysis',legacy:'14-1',title:'로마숫자 분석',summary:'조성·근음·성질·전위·변화음을 순서대로 분석합니다.',objective:'복합 화음 진행을 로마숫자와 전위로 표기한다.',prerequisiteRefs:['harmony.lesson.chromatic-modulation.lesson'],markdown:'로마숫자 분석은 먼저 조성과 구절을 찾고, 각 화음의 근음·성질·전위를 판별합니다. 변화화음은 **V/x, vii°/x, 차용화음** 가능성을 문맥에서 비교합니다.',groups:[I,[D4,Fs4,A4,C5],V,I],activityTitle:'I–V7/V–V–I 분석',prompt:'C장조에서 D–F♯–A–C가 G로 진행하면?',options:opts('V7/V','ii7','♭II7'),answer:'o1',explanation:'D7은 G(V)의 도미넌트이므로 V7/V입니다.',items:['조성과 구절 경계를 먼저 봅니다.','근음·성질·전위를 판별합니다.','변화화음은 해결 화음까지 확인합니다.']}),
lesson({key:'lesson.advanced-function-analysis',legacy:'14-2',title:'기능 분석',summary:'로마숫자를 T·S·D와 확장 기능 흐름으로 해석합니다.',objective:'대리·적용·반음계 화음이 포함된 기능 흐름을 설명한다.',prerequisiteRefs:['harmony.lesson.advanced-roman-analysis.lesson'],markdown:'기능 분석은 코드 이름을 나열하는 것이 아니라 **안정–준비–긴장–해결**의 방향을 읽습니다. 적용화음은 잠시 다른 화음을 D–T 관계로 강조할 수 있습니다.',groups:[vi,ii,[D4,Fs4,A4,C5],V,I],activityTitle:'T대리–S–D/V–D–T',prompt:'vi–ii–V7/V–V–I의 큰 종착 기능은?',options:opts('Dominant에서 Tonic으로 해결','Tonic에서 Subdominant로 끝남','기능 방향이 없음'),answer:'o1',explanation:'확장된 Dominant 영역이 마지막 I로 해결됩니다.',items:['대리화음을 기능군으로 묶습니다.','적용화음은 목표 화음을 강조합니다.','구절의 최종 긴장과 해결을 봅니다.']}),
lesson({key:'lesson.piece-analysis',legacy:'14-3',title:'악곡 분석',summary:'구절·종지·조성·성부를 계층적으로 읽습니다.',objective:'짧은 악곡의 구절과 화성 사건을 분석 순서대로 설명한다.',prerequisiteRefs:['harmony.lesson.advanced-function-analysis.lesson'],markdown:'악곡 분석은 세부 화음부터 시작하지 않습니다. 먼저 **형식과 구절**, 종지와 조성 중심을 찾고, 그 안에서 로마숫자·기능·비화성음·성부진행을 해석합니다.',groups:[I,IV,V,I,vi,ii,V,I],activityTitle:'두 구절의 종지와 기능 비교',prompt:'악곡 분석에서 가장 먼저 확인할 층위는?',options:opts('형식과 구절 경계','모든 장식음 이름','마지막 한 음의 높이'),answer:'o1',explanation:'큰 구절 구조가 개별 화음의 기능과 종지 문맥을 결정합니다.',items:['큰 형식에서 세부로 내려갑니다.','종지와 조성 중심을 찾습니다.','화음·비화성음·성부진행을 종합합니다.']}),
lesson({key:'lesson.score-analysis-practice',legacy:'14-4',title:'악보 분석 실습',summary:'하나의 화음을 문맥에 따라 복수 해석하고 근거를 비교합니다.',objective:'복수의 허용 가능한 화성 해석을 근거와 함께 제시한다.',prerequisiteRefs:['harmony.lesson.piece-analysis.lesson'],markdown:'실제 악보에서는 하나의 화음이 둘 이상의 분석을 허용할 수 있습니다. C장조의 D7–G–C는 보통 **V7/V–V–I**지만, 넓은 구절에서는 반음계적 프리도미넌트로 설명할 여지도 있습니다. 자동 판정은 선언된 해석만 다루며 전문가 검수 경계를 유지합니다.',groups:[[D4,Fs4,A4,C5],V,I],activityTitle:'D7–G–C의 문맥 분석',prompt:'C장조 D7–G–C의 가장 직접적인 분석은?',options:opts('V7/V–V–I','ii7–V–I','iv–V–I'),answer:'o1',explanation:'D7은 G를 잠시 강조하는 V7/V이며 G는 V, C는 I입니다.',items:['분석에는 문맥과 근거가 필요합니다.','복수 해석 가능성을 명시할 수 있습니다.','자동 판정과 전문가 검수의 경계를 둡니다.']})]};

export const batchEPart15Before:Lesson[]=[lesson({key:'lesson.voice-leading-basics',legacy:'15-1',title:'성부 진행',summary:'각 성부를 독립적인 선율로 연결하는 기본 원칙을 봅니다.',objective:'공통음 유지와 순차 진행을 사용해 성부를 연결한다.',prerequisiteRefs:['harmony.lesson.score-analysis-practice.lesson'],markdown:'성부 진행은 화음 사이에서 각 성부가 어떻게 이동하는지 다룹니다. 공통음은 가능하면 유지하고, 나머지는 가까운 화음음으로 움직여 각 성부의 선율성과 독립성을 지킵니다.',groups:[[C3,G3,E4,C5],[G3,G4,B4,D5]],activityTitle:'I에서 V로 성부 이동',prompt:'부드러운 성부 진행의 기본 전략은?',options:opts('공통음 유지와 가까운 음 이동','모든 성부를 같은 방향 도약','항상 음을 중복하지 않음'),answer:'o1',explanation:'공통음을 유지하고 가까운 구성음으로 이동하면 불필요한 도약을 줄입니다.',items:['각 성부를 선율로 봅니다.','공통음을 유지합니다.','가까운 구성음으로 이동합니다.']})];

export const batchEPart15After:Lesson[]=[
lesson({key:'lesson.voice-spacing',legacy:'15-3',title:'성부 배치',summary:'SATB의 음역·간격·중복 원칙을 확인합니다.',objective:'4성부의 올바른 음역과 상성부 간격을 판별한다.',prerequisiteRefs:['harmony.lesson.voice-leading'],markdown:'SATB 배치에서 소프라노–알토와 알토–테너는 보통 옥타브 이내로 두고, 테너–베이스는 더 넓을 수 있습니다. 성부 교차와 무리한 음역을 피합니다.',groups:[[C3,G3,E4,C5],[C3,E4,G4,C5]],activityTitle:'좁은 배치와 열린 배치 비교',prompt:'일반적으로 옥타브 이내를 유지하는 인접 성부는?',options:opts('소프라노–알토, 알토–테너','테너–베이스만','모든 성부가 반드시 3도 이내'),answer:'o1',explanation:'상위 세 성부의 인접 간격은 보통 옥타브 이내로 관리합니다.',items:['각 성부의 음역을 지킵니다.','상성부 간격을 점검합니다.','성부 교차를 피합니다.']}),
lesson({key:'lesson.connection-rules',legacy:'15-4',title:'연결 규칙',summary:'공통음과 반대진행으로 화음을 안정적으로 연결합니다.',objective:'화음 연결에서 공통음·선율·금지 병행을 함께 점검한다.',prerequisiteRefs:['harmony.lesson.voice-spacing.lesson'],markdown:'연결 규칙은 기계적인 금지 목록이 아니라 독립적인 성부를 만드는 도구입니다. 공통음을 유지하고 반대·사행 진행을 활용하며 병행5도·8도와 과도한 도약을 점검합니다.',groups:[[C3,G3,E4,C5],[G3,D4,G4,B4],[C3,E4,G4,C5]],activityTitle:'I–V–I 연결 비교',prompt:'외성의 독립성을 높이는 데 유리한 진행은?',options:opts('반대진행','모든 성부의 같은 방향','모든 성부의 같은 음 유지'),answer:'o1',explanation:'한 성부가 올라갈 때 다른 성부가 내려가는 반대진행은 독립성을 높입니다.',items:['공통음은 유지합니다.','반대진행을 활용합니다.','병행 완전음정을 점검합니다.']}),
lesson({key:'lesson.cadence-writing',legacy:'15-5',title:'종지 작성',summary:'베이스·소프라노·내성을 함께 설계해 종지를 완성합니다.',objective:'완전정격종지의 외성 조건과 내성 해결을 적용한다.',prerequisiteRefs:['harmony.lesson.connection-rules.lesson'],markdown:'완전정격종지는 V–I가 기본형으로 연결되고 소프라노가 으뜸음으로 끝납니다. 이끎음은 으뜸음으로, V7의 7음은 아래로 해결하는 것이 기본입니다.',groups:[[G3,D4,F4,B4],[C3,E4,G4,C5]],activityTitle:'V7–I 완전정격종지',prompt:'완전정격종지의 소프라노 마지막 음은?',options:opts('으뜸음','3음만 가능','5음만 가능'),answer:'o1',explanation:'두 화음이 기본형이고 소프라노가 으뜸음으로 끝나야 완전정격종지입니다.',items:['V–I 기본형을 사용합니다.','소프라노가 으뜸음으로 끝납니다.','경향음을 올바르게 해결합니다.']}),
lesson({key:'lesson.four-part-harmony',legacy:'15-6',title:'4성부 화성',summary:'화음 선택·배치·연결을 하나의 절차로 통합합니다.',objective:'주어진 베이스에 SATB 화성을 단계적으로 완성한다.',prerequisiteRefs:['harmony.lesson.cadence-writing.lesson'],markdown:'4성부 화성은 조성과 기능을 정한 뒤 베이스·소프라노의 큰 선율을 만들고 내성을 채웁니다. 마지막에 음역·중복·간격·경향음·병행을 종합 점검합니다.',groups:[[C3,G3,E4,C5],[F4,A4,C5,F5],[G3,D4,G4,B4],[C3,E4,G4,C5]],activityTitle:'I–IV–V–I 4성부 배치',prompt:'4성부 화성 검토의 올바른 순서는?',options:opts('기능·외성 설계 후 세부 규칙 점검','병행만 확인하고 기능은 무시','내성부터 무작위로 채움'),answer:'o1',explanation:'큰 기능과 외성 선율을 먼저 정한 뒤 세부 연결을 점검합니다.',items:['기능과 종지를 먼저 설계합니다.','외성의 선율을 확인합니다.','음역·중복·병행·경향음을 종합 점검합니다.']})];

export const batchEPart16:Part={id:'harmony.part.styles',title:'PART 16. 양식과 종합',lessons:[
lesson({key:'lesson.chorale-analysis',legacy:'16-1',title:'코랄 분석',summary:'4성부 코랄에서 구절·종지·성부진행을 종합합니다.',objective:'코랄의 구절별 로마숫자·종지·성부진행을 분석한다.',prerequisiteRefs:['harmony.lesson.four-part-harmony.lesson'],markdown:'코랄 분석은 프레이즈와 종지를 표시한 뒤 베이스를 바탕으로 로마숫자를 적고, 비화성음과 성부진행을 검토합니다. 수직 화음과 수평 선율을 함께 읽습니다.',groups:[I,IV,V,I,vi,ii,V,I],activityTitle:'두 프레이즈의 기능과 종지',prompt:'코랄 분석에서 수직 화음과 함께 반드시 볼 것은?',options:opts('각 성부의 수평 선율','악기 음색만','템포 숫자만'),answer:'o1',explanation:'코랄은 네 성부의 독립적인 선율이 화음을 이루므로 수평·수직을 함께 봅니다.',items:['프레이즈와 종지를 찾습니다.','베이스와 로마숫자를 연결합니다.','각 성부의 선율과 비화성음을 봅니다.']}),
lesson({key:'lesson.classical-harmony',legacy:'16-2',title:'고전 화성',summary:'명료한 기능·주기적 구절·종지 중심의 어법을 봅니다.',objective:'고전 화성의 기능적 명료성과 형식 균형을 설명한다.',prerequisiteRefs:['harmony.lesson.chorale-analysis.lesson'],markdown:'고전 화성은 T–S–D–T 기능이 비교적 명료하고, 주기적인 구절과 종지가 형식을 분명히 합니다. 변화화음도 목표와 해결이 선명한 경우가 많습니다.',groups:[I,IV,V,I,ii,V,I],activityTitle:'명료한 기능과 종지',prompt:'고전 화성의 대표적 특징은?',options:opts('명료한 기능과 균형 잡힌 구절','기능을 완전히 배제','항상 같은 화음만 반복'),answer:'o1',explanation:'고전 양식은 기능 진행과 종지로 형식적 균형을 선명하게 만듭니다.',items:['기능 진행이 명료합니다.','구절과 종지가 형식을 만듭니다.','변화화음의 목표와 해결이 비교적 분명합니다.']}),
lesson({key:'lesson.romantic-harmony',legacy:'16-3',title:'낭만 화성',summary:'반음계·확장된 Dominant·먼 조성 전조를 탐색합니다.',objective:'낭만 화성의 반음계적 확장과 조성 모호성을 설명한다.',prerequisiteRefs:['harmony.lesson.classical-harmony.lesson'],markdown:'낭만 화성은 차용화음·증6화음·확장된 도미넌트·먼 조성 전조로 긴장을 오래 유지합니다. 기능은 사라지기보다 지연되고 중첩되며 때로 중심이 모호해집니다.',groups:[[F4,A4,C5],[F4,p('A',4,-1),C5],[p('A',4,-1),C5,Fs4],V,I],activityTitle:'차용·증6·Dominant의 확장',prompt:'낭만 화성에서 자주 나타나는 현상은?',options:opts('반음계와 지연된 해결','변화음의 완전한 금지','항상 한 조성의 I–V만 사용'),answer:'o1',explanation:'반음계적 화음과 먼 전조가 긴장과 조성 영역을 확장합니다.',items:['반음계 사용이 확대됩니다.','Dominant 영역과 해결이 연장됩니다.','먼 조성 전조와 모호성이 나타납니다.']}),
lesson({key:'lesson.pop-harmony',legacy:'16-4',title:'현대 대중음악 화성',summary:'루프·선법·차용화음과 음색의 역할을 함께 봅니다.',objective:'대중음악의 반복 진행을 기능과 선법 관점에서 분석한다.',prerequisiteRefs:['harmony.lesson.romantic-harmony.lesson'],markdown:'현대 대중음악은 I–V–vi–IV 같은 루프, 선법적 ♭VII, 차용 iv 등을 자주 사용합니다. 전통 종지뿐 아니라 반복·베이스·리듬·음색이 조성감을 만듭니다.',groups:[I,V,vi,IV,[Bb4,D5,F5],I],activityTitle:'I–V–vi–IV와 ♭VII 색채',prompt:'대중음악 루프 분석에서 화음 외에 함께 볼 요소는?',options:opts('베이스·리듬·음색과 반복','오직 마지막 종지만','악보의 글꼴'),answer:'o1',explanation:'반복 구조와 사운드 요소가 화성의 기능과 조성 체감에 큰 영향을 줍니다.',items:['루프의 반복 구조를 봅니다.','선법과 차용화음을 고려합니다.','베이스·리듬·음색도 분석 대상입니다.']}),
lesson({key:'lesson.comprehensive-practice',legacy:'16-5',title:'종합 연습',summary:'조성부터 성부진행까지 분석 근거를 단계적으로 정리합니다.',objective:'짧은 진행을 조성·화음·기능·종지·성부 관점에서 종합 분석한다.',prerequisiteRefs:['harmony.lesson.pop-harmony.lesson'],markdown:'종합 분석은 정답 표기보다 근거의 순서가 중요합니다. **조성과 구절 → 로마숫자와 기능 → 비화성음·전조 → 종지와 성부진행 → 양식적 특징** 순으로 검토합니다.',groups:[I,[D4,Fs4,A4,C5],V,I,vi,ii,V,I],activityTitle:'전체 개념을 연결한 진행',prompt:'종합 분석의 가장 적절한 시작은?',options:opts('조성과 구절 경계 확인','장식음 하나에 이름 붙이기','모든 화음을 조성 없이 표기'),answer:'o1',explanation:'큰 조성·구절 문맥을 먼저 정해야 개별 화음과 음의 역할을 해석할 수 있습니다.',items:['큰 문맥에서 세부로 분석합니다.','각 판단에 음악적 근거를 붙입니다.','복수 해석과 전문가 검수 경계를 인정합니다.']})]};
