/* This file is generated by scripts/generate-harmony-checkpoint-blocks.mjs. */
import { blockVersion, type Book } from '@interactive-textbook/schema';

export const legacyCheckpointMappings = [
  {
    "id": "harmony.checkpoint.3.1",
    "part": 3,
    "targetLessonId": "harmony.lesson.major-key.lesson",
    "prompt": "장음계의 음정 패턴은?",
    "options": [
      {
        "id": "choice-1",
        "label": "온-온-반-온-온-온-반"
      },
      {
        "id": "choice-2",
        "label": "온-반-온-온-반-온-온"
      },
      {
        "id": "choice-3",
        "label": "온-온-온-반-온-온-반"
      },
      {
        "id": "choice-4",
        "label": "반-온-온-반-온-온-온"
      }
    ],
    "answer": "choice-1",
    "explanation": "장음계는 온-온-반-온-온-온-반의 구조를 가진다."
  },
  {
    "id": "harmony.checkpoint.3.2",
    "part": 3,
    "targetLessonId": "harmony.lesson.key-signature.lesson",
    "prompt": "G장조의 조표는?",
    "options": [
      {
        "id": "choice-1",
        "label": "B♭ 1개"
      },
      {
        "id": "choice-2",
        "label": "F♯·C♯ 2개"
      },
      {
        "id": "choice-3",
        "label": "조표 없음"
      },
      {
        "id": "choice-4",
        "label": "F♯ 1개"
      }
    ],
    "answer": "choice-4",
    "explanation": "G장조는 F♯ 한 음을 올린다."
  },
  {
    "id": "harmony.checkpoint.3.3",
    "part": 3,
    "targetLessonId": "harmony.lesson.related-keys.lesson",
    "prompt": "C장조의 나란한 단조는?",
    "options": [
      {
        "id": "choice-1",
        "label": "E단조"
      },
      {
        "id": "choice-2",
        "label": "G단조"
      },
      {
        "id": "choice-3",
        "label": "A단조"
      },
      {
        "id": "choice-4",
        "label": "C단조"
      }
    ],
    "answer": "choice-3",
    "explanation": "나란한조는 같은 조표를 공유하며 C장조의 나란한 단조는 A단조다."
  },
  {
    "id": "harmony.checkpoint.3.4",
    "part": 3,
    "targetLessonId": "harmony.lesson.circle-of-fifths.lesson",
    "prompt": "5도권에서 C에서 시계방향 한 칸은?",
    "options": [
      {
        "id": "choice-1",
        "label": "A단조"
      },
      {
        "id": "choice-2",
        "label": "G장조"
      },
      {
        "id": "choice-3",
        "label": "F장조"
      },
      {
        "id": "choice-4",
        "label": "D장조"
      }
    ],
    "answer": "choice-2",
    "explanation": "시계방향은 완전5도 위로 이동하며 샵이 하나 증가한다."
  },
  {
    "id": "harmony.checkpoint.4.1",
    "part": 4,
    "targetLessonId": "harmony.lesson.triad",
    "prompt": "장3화음의 내부 구조는?",
    "options": [
      {
        "id": "choice-1",
        "label": "단3도 + 장3도"
      },
      {
        "id": "choice-2",
        "label": "장3도 + 장3도"
      },
      {
        "id": "choice-3",
        "label": "단3도 + 단3도"
      },
      {
        "id": "choice-4",
        "label": "장3도 + 단3도"
      }
    ],
    "answer": "choice-4",
    "explanation": "장3화음은 근음-3음이 장3도, 3음-5음이 단3도다."
  },
  {
    "id": "harmony.checkpoint.4.2",
    "part": 4,
    "targetLessonId": "harmony.lesson.triad-inversion.lesson",
    "prompt": "C장3화음의 제1전위는?",
    "options": [
      {
        "id": "choice-1",
        "label": "C-E-G"
      },
      {
        "id": "choice-2",
        "label": "E-C-G"
      },
      {
        "id": "choice-3",
        "label": "E-G-C"
      },
      {
        "id": "choice-4",
        "label": "G-C-E"
      }
    ],
    "answer": "choice-3",
    "explanation": "제1전위는 3음이 베이스에 온다."
  },
  {
    "id": "harmony.checkpoint.4.3",
    "part": 4,
    "targetLessonId": "harmony.lesson.triad",
    "prompt": "감3화음의 내부 구조는?",
    "options": [
      {
        "id": "choice-1",
        "label": "장3도 + 장3도"
      },
      {
        "id": "choice-2",
        "label": "단3도 + 단3도"
      },
      {
        "id": "choice-3",
        "label": "장3도 + 단3도"
      },
      {
        "id": "choice-4",
        "label": "단3도 + 장3도"
      }
    ],
    "answer": "choice-2",
    "explanation": "감3화음은 두 개의 단3도를 쌓는다."
  },
  {
    "id": "harmony.checkpoint.4.4",
    "part": 4,
    "targetLessonId": "harmony.lesson.chord-symbols.lesson",
    "prompt": "로마숫자 분석의 장점은?",
    "options": [
      {
        "id": "choice-1",
        "label": "조성 안의 상대적 기능을 보여준다"
      },
      {
        "id": "choice-2",
        "label": "항상 실제 음이름만 보여준다"
      },
      {
        "id": "choice-3",
        "label": "리듬을 표시한다"
      },
      {
        "id": "choice-4",
        "label": "템포를 결정한다"
      }
    ],
    "answer": "choice-1",
    "explanation": "로마숫자는 조가 바뀌어도 도수와 기능 관계를 유지한다."
  },
  {
    "id": "harmony.checkpoint.5.1",
    "part": 5,
    "targetLessonId": "harmony.lesson.seventh-types.lesson",
    "prompt": "도미넌트7화음의 구조는?",
    "options": [
      {
        "id": "choice-1",
        "label": "감3화음 + 단7도"
      },
      {
        "id": "choice-2",
        "label": "장3화음 + 장7도"
      },
      {
        "id": "choice-3",
        "label": "장3화음 + 단7도"
      },
      {
        "id": "choice-4",
        "label": "단3화음 + 장7도"
      }
    ],
    "answer": "choice-3",
    "explanation": "V7은 장3화음 위에 단7도가 더해진 구조다."
  },
  {
    "id": "harmony.checkpoint.5.2",
    "part": 5,
    "targetLessonId": "harmony.lesson.seventh-inversion.lesson",
    "prompt": "7화음의 제3전위는 무엇이 베이스인가?",
    "options": [
      {
        "id": "choice-1",
        "label": "5음"
      },
      {
        "id": "choice-2",
        "label": "7음"
      },
      {
        "id": "choice-3",
        "label": "근음"
      },
      {
        "id": "choice-4",
        "label": "3음"
      }
    ],
    "answer": "choice-2",
    "explanation": "제3전위에서는 화음의 7음이 최저음이다."
  },
  {
    "id": "harmony.checkpoint.5.3",
    "part": 5,
    "targetLessonId": "harmony.lesson.seventh-resolution.lesson",
    "prompt": "G7에서 F의 일반적인 해결 방향은?",
    "options": [
      {
        "id": "choice-1",
        "label": "E로 하행"
      },
      {
        "id": "choice-2",
        "label": "G로 상행"
      },
      {
        "id": "choice-3",
        "label": "F♯로 상행"
      },
      {
        "id": "choice-4",
        "label": "D로 도약"
      }
    ],
    "answer": "choice-1",
    "explanation": "화음의 7음은 일반적으로 순차 하행한다."
  },
  {
    "id": "harmony.checkpoint.5.4",
    "part": 5,
    "targetLessonId": "harmony.lesson.seventh-resolution.lesson",
    "prompt": "G7에서 B의 일반적인 해결 방향은?",
    "options": [
      {
        "id": "choice-1",
        "label": "A로 하행"
      },
      {
        "id": "choice-2",
        "label": "D로 상행"
      },
      {
        "id": "choice-3",
        "label": "F로 하행"
      },
      {
        "id": "choice-4",
        "label": "C로 상행"
      }
    ],
    "answer": "choice-4",
    "explanation": "B는 C장조의 이끎음이므로 C로 해결하는 경향이 강하다."
  },
  {
    "id": "harmony.checkpoint.6.1",
    "part": 6,
    "targetLessonId": "harmony.lesson.major-diatonic.lesson",
    "prompt": "장조의 다이어토닉 3화음 패턴은?",
    "options": [
      {
        "id": "choice-1",
        "label": "대-소-대-소-대-소-감"
      },
      {
        "id": "choice-2",
        "label": "대-소-소-대-대-소-감"
      },
      {
        "id": "choice-3",
        "label": "대-대-소-소-대-감-소"
      },
      {
        "id": "choice-4",
        "label": "소-감-대-소-소-대-대"
      }
    ],
    "answer": "choice-2",
    "explanation": "I ii iii IV V vi vii°의 화음 성질이다."
  },
  {
    "id": "harmony.checkpoint.6.2",
    "part": 6,
    "targetLessonId": "harmony.lesson.major-diatonic.lesson",
    "prompt": "C장조의 ii는?",
    "options": [
      {
        "id": "choice-1",
        "label": "Dm"
      },
      {
        "id": "choice-2",
        "label": "D"
      },
      {
        "id": "choice-3",
        "label": "Em"
      },
      {
        "id": "choice-4",
        "label": "F"
      }
    ],
    "answer": "choice-1",
    "explanation": "2도 D 위에 다이어토닉 3도를 쌓으면 D-F-A, Dm이다."
  },
  {
    "id": "harmony.checkpoint.6.3",
    "part": 6,
    "targetLessonId": "harmony.lesson.function-basics.lesson",
    "prompt": "기능 흐름의 대표적인 방향은?",
    "options": [
      {
        "id": "choice-1",
        "label": "D → T → PD → D"
      },
      {
        "id": "choice-2",
        "label": "PD → T → D → PD"
      },
      {
        "id": "choice-3",
        "label": "T → D → T → PD"
      },
      {
        "id": "choice-4",
        "label": "T → PD → D → T"
      }
    ],
    "answer": "choice-4",
    "explanation": "안정에서 준비, 긴장, 해결로 향하는 흐름이 기본이다."
  },
  {
    "id": "harmony.checkpoint.6.4",
    "part": 6,
    "targetLessonId": "harmony.lesson.minor-diatonic.lesson",
    "prompt": "단조에서 V를 장화음으로 만드는 핵심 변화는?",
    "options": [
      {
        "id": "choice-1",
        "label": "4음을 올린다"
      },
      {
        "id": "choice-2",
        "label": "6음을 내린다"
      },
      {
        "id": "choice-3",
        "label": "7음을 올려 이끎음을 만든다"
      },
      {
        "id": "choice-4",
        "label": "2음을 내린다"
      }
    ],
    "answer": "choice-3",
    "explanation": "화성단음계의 올린 7음이 장도미넌트와 이끎음을 만든다."
  },
  {
    "id": "harmony.checkpoint.7.1",
    "part": 7,
    "targetLessonId": "harmony.lesson.tonic-function.lesson",
    "prompt": "가장 강한 토닉 기능은?",
    "options": [
      {
        "id": "choice-1",
        "label": "I"
      },
      {
        "id": "choice-2",
        "label": "ii"
      },
      {
        "id": "choice-3",
        "label": "IV"
      },
      {
        "id": "choice-4",
        "label": "V"
      }
    ],
    "answer": "choice-1",
    "explanation": "I는 조성 중심을 가장 직접적으로 확립한다."
  },
  {
    "id": "harmony.checkpoint.7.2",
    "part": 7,
    "targetLessonId": "harmony.lesson.subdominant-function.lesson",
    "prompt": "대표적인 프리도미넌트 화음은?",
    "options": [
      {
        "id": "choice-1",
        "label": "I와 vi"
      },
      {
        "id": "choice-2",
        "label": "V와 vii°"
      },
      {
        "id": "choice-3",
        "label": "iii와 V"
      },
      {
        "id": "choice-4",
        "label": "ii와 IV"
      }
    ],
    "answer": "choice-4",
    "explanation": "ii와 IV는 도미넌트를 준비하는 대표 화음이다."
  },
  {
    "id": "harmony.checkpoint.7.3",
    "part": 7,
    "targetLessonId": "harmony.lesson.dominant-function.lesson",
    "prompt": "대표적인 도미넌트 기능은?",
    "options": [
      {
        "id": "choice-1",
        "label": "ii와 IV"
      },
      {
        "id": "choice-2",
        "label": "iii와 vi"
      },
      {
        "id": "choice-3",
        "label": "V와 vii°"
      },
      {
        "id": "choice-4",
        "label": "I와 vi"
      }
    ],
    "answer": "choice-3",
    "explanation": "V와 vii°는 이끎음을 포함해 토닉으로 강하게 향한다."
  },
  {
    "id": "harmony.checkpoint.7.4",
    "part": 7,
    "targetLessonId": "harmony.lesson.function-connection.lesson",
    "prompt": "I-vi-ii-V-I의 기능 흐름은?",
    "options": [
      {
        "id": "choice-1",
        "label": "T-PD-T-D-PD"
      },
      {
        "id": "choice-2",
        "label": "T-T-PD-D-T"
      },
      {
        "id": "choice-3",
        "label": "T-D-PD-T-D"
      },
      {
        "id": "choice-4",
        "label": "PD-T-D-PD-T"
      }
    ],
    "answer": "choice-2",
    "explanation": "vi는 토닉 영역, ii는 프리도미넌트, V는 도미넌트다."
  },
  {
    "id": "harmony.checkpoint.8.1",
    "part": 8,
    "targetLessonId": "harmony.lesson.authentic-cadence.lesson",
    "prompt": "정격종지의 핵심 진행은?",
    "options": [
      {
        "id": "choice-1",
        "label": "IV → I"
      },
      {
        "id": "choice-2",
        "label": "V → vi"
      },
      {
        "id": "choice-3",
        "label": "I → V"
      },
      {
        "id": "choice-4",
        "label": "V → I"
      }
    ],
    "answer": "choice-4",
    "explanation": "도미넌트에서 토닉으로 해결한다."
  },
  {
    "id": "harmony.checkpoint.8.2",
    "part": 8,
    "targetLessonId": "harmony.lesson.half-cadence.lesson",
    "prompt": "반종지는 어디에서 끝나는가?",
    "options": [
      {
        "id": "choice-1",
        "label": "IV"
      },
      {
        "id": "choice-2",
        "label": "vi"
      },
      {
        "id": "choice-3",
        "label": "V"
      },
      {
        "id": "choice-4",
        "label": "I"
      }
    ],
    "answer": "choice-3",
    "explanation": "V에서 멈춰 열린 느낌을 남긴다."
  },
  {
    "id": "harmony.checkpoint.8.3",
    "part": 8,
    "targetLessonId": "harmony.lesson.deceptive-cadence.lesson",
    "prompt": "기만종지의 대표 진행은?",
    "options": [
      {
        "id": "choice-1",
        "label": "V → I"
      },
      {
        "id": "choice-2",
        "label": "V → vi"
      },
      {
        "id": "choice-3",
        "label": "IV → I"
      },
      {
        "id": "choice-4",
        "label": "ii → V"
      }
    ],
    "answer": "choice-2",
    "explanation": "예상된 I 대신 vi 등으로 진행해 종결을 미룬다."
  },
  {
    "id": "harmony.checkpoint.8.4",
    "part": 8,
    "targetLessonId": "harmony.lesson.plagal-cadence.lesson",
    "prompt": "변격종지의 핵심 진행은?",
    "options": [
      {
        "id": "choice-1",
        "label": "IV → I"
      },
      {
        "id": "choice-2",
        "label": "V → I"
      },
      {
        "id": "choice-3",
        "label": "V → vi"
      },
      {
        "id": "choice-4",
        "label": "I → IV"
      }
    ],
    "answer": "choice-1",
    "explanation": "IV에서 I로 진행하는 부드러운 종결이다."
  },
  {
    "id": "harmony.checkpoint.9.1",
    "part": 9,
    "targetLessonId": "harmony.lesson.circle-progression.lesson",
    "prompt": "ii-V-I에서 근음 진행의 특징은?",
    "options": [
      {
        "id": "choice-1",
        "label": "3도 하행만 반복"
      },
      {
        "id": "choice-2",
        "label": "반음만 이동"
      },
      {
        "id": "choice-3",
        "label": "5도 하행/4도 상행"
      },
      {
        "id": "choice-4",
        "label": "2도 상행만 반복"
      }
    ],
    "answer": "choice-3",
    "explanation": "D→G→C처럼 강한 5도 순환을 만든다."
  },
  {
    "id": "harmony.checkpoint.9.2",
    "part": 9,
    "targetLessonId": "harmony.lesson.basic-progression.lesson",
    "prompt": "I-V-vi-IV를 다른 조로 옮겨도 유지되는 것은?",
    "options": [
      {
        "id": "choice-1",
        "label": "절대 음높이"
      },
      {
        "id": "choice-2",
        "label": "로마숫자 구조"
      },
      {
        "id": "choice-3",
        "label": "실제 음이름"
      },
      {
        "id": "choice-4",
        "label": "조표"
      }
    ],
    "answer": "choice-2",
    "explanation": "전조해도 상대적 도수 구조는 유지된다."
  },
  {
    "id": "harmony.checkpoint.9.3",
    "part": 9,
    "targetLessonId": "harmony.lesson.repeated-progression.lesson",
    "prompt": "순차 진행이란?",
    "options": [
      {
        "id": "choice-1",
        "label": "같은 음정/화성 패턴의 반복"
      },
      {
        "id": "choice-2",
        "label": "한 화음만 지속"
      },
      {
        "id": "choice-3",
        "label": "무조건 V-I"
      },
      {
        "id": "choice-4",
        "label": "모든 음을 반음씩 이동"
      }
    ],
    "answer": "choice-1",
    "explanation": "패턴이 다른 음높이에서 반복되는 것이 핵심이다."
  },
  {
    "id": "harmony.checkpoint.9.4",
    "part": 9,
    "targetLessonId": "harmony.lesson.common-progressions.lesson",
    "prompt": "반복 진행의 장점은?",
    "options": [
      {
        "id": "choice-1",
        "label": "항상 강한 전조를 만든다"
      },
      {
        "id": "choice-2",
        "label": "반드시 불협화를 만든다"
      },
      {
        "id": "choice-3",
        "label": "리듬을 없앤다"
      },
      {
        "id": "choice-4",
        "label": "안정과 강조를 만든다"
      }
    ],
    "answer": "choice-4",
    "explanation": "화성 변화가 적어 다른 요소를 강조할 수 있다."
  },
  {
    "id": "harmony.checkpoint.10.1",
    "part": 10,
    "targetLessonId": "harmony.lesson.passing-tone.lesson",
    "prompt": "경과음의 전형적 움직임은?",
    "options": [
      {
        "id": "choice-1",
        "label": "다음 화음음을 미리 연주"
      },
      {
        "id": "choice-2",
        "label": "두 화음음을 순차적으로 연결"
      },
      {
        "id": "choice-3",
        "label": "도약 후 같은 음으로 복귀"
      },
      {
        "id": "choice-4",
        "label": "앞 화음을 강박까지 유지"
      }
    ],
    "answer": "choice-2",
    "explanation": "경과음은 화음음 사이를 순차 연결한다."
  },
  {
    "id": "harmony.checkpoint.10.2",
    "part": 10,
    "targetLessonId": "harmony.lesson.neighbor-tone.lesson",
    "prompt": "보조음의 특징은?",
    "options": [
      {
        "id": "choice-1",
        "label": "인접음으로 벗어났다가 원음으로 복귀"
      },
      {
        "id": "choice-2",
        "label": "항상 도약으로 진입"
      },
      {
        "id": "choice-3",
        "label": "반드시 강박에만 등장"
      },
      {
        "id": "choice-4",
        "label": "다음 화음음을 미리 제시"
      }
    ],
    "answer": "choice-1",
    "explanation": "출발한 화음음으로 돌아온다."
  },
  {
    "id": "harmony.checkpoint.10.3",
    "part": 10,
    "targetLessonId": "harmony.lesson.suspension.lesson",
    "prompt": "계류음의 세 단계는?",
    "options": [
      {
        "id": "choice-1",
        "label": "도약-반복-종지"
      },
      {
        "id": "choice-2",
        "label": "선행-도약-반복"
      },
      {
        "id": "choice-3",
        "label": "준비-전조-종지"
      },
      {
        "id": "choice-4",
        "label": "준비-계류-해결"
      }
    ],
    "answer": "choice-4",
    "explanation": "앞 화음에서 준비된 음이 유지되어 불협화를 만든 뒤 해결한다."
  },
  {
    "id": "harmony.checkpoint.10.4",
    "part": 10,
    "targetLessonId": "harmony.lesson.appoggiatura.lesson",
    "prompt": "선행음은 무엇을 미리 들려주는가?",
    "options": [
      {
        "id": "choice-1",
        "label": "조표"
      },
      {
        "id": "choice-2",
        "label": "베이스만"
      },
      {
        "id": "choice-3",
        "label": "다음 화음의 음"
      },
      {
        "id": "choice-4",
        "label": "이전 화음의 근음"
      }
    ],
    "answer": "choice-3",
    "explanation": "새 화음의 구성음이 화음 변화보다 먼저 나온다."
  },
  {
    "id": "harmony.checkpoint.11.1",
    "part": 11,
    "targetLessonId": "harmony.lesson.secondary-dominant.lesson",
    "prompt": "C장조에서 V/V는?",
    "options": [
      {
        "id": "choice-1",
        "label": "D 또는 D7"
      },
      {
        "id": "choice-2",
        "label": "F 또는 F7"
      },
      {
        "id": "choice-3",
        "label": "A♭ 또는 A♭7"
      },
      {
        "id": "choice-4",
        "label": "C 또는 C7"
      }
    ],
    "answer": "choice-1",
    "explanation": "G(V)의 도미넌트는 D다."
  },
  {
    "id": "harmony.checkpoint.11.2",
    "part": 11,
    "targetLessonId": "harmony.lesson.secondary-dominant.lesson",
    "prompt": "C장조에서 vii°/V의 근음은?",
    "options": [
      {
        "id": "choice-1",
        "label": "F"
      },
      {
        "id": "choice-2",
        "label": "B♭"
      },
      {
        "id": "choice-3",
        "label": "C♯"
      },
      {
        "id": "choice-4",
        "label": "F♯"
      }
    ],
    "answer": "choice-4",
    "explanation": "G의 이끎음 F♯ 위에 감화음을 만든다."
  },
  {
    "id": "harmony.checkpoint.11.3",
    "part": 11,
    "targetLessonId": "harmony.lesson.applied-chord.lesson",
    "prompt": "적용화음의 핵심 효과는?",
    "options": [
      {
        "id": "choice-1",
        "label": "리듬을 바꿈"
      },
      {
        "id": "choice-2",
        "label": "모든 음을 반음 내림"
      },
      {
        "id": "choice-3",
        "label": "다른 다이어토닉 화음을 잠시 토닉화"
      },
      {
        "id": "choice-4",
        "label": "영구적으로 조성을 없앰"
      }
    ],
    "answer": "choice-3",
    "explanation": "목표 화음을 일시적 중심처럼 들리게 한다."
  },
  {
    "id": "harmony.checkpoint.11.4",
    "part": 11,
    "targetLessonId": "harmony.lesson.applied-chord.lesson",
    "prompt": "토닉화와 전조의 차이는?",
    "options": [
      {
        "id": "choice-1",
        "label": "박자표"
      },
      {
        "id": "choice-2",
        "label": "새 조의 지속성과 기능 확립 정도"
      },
      {
        "id": "choice-3",
        "label": "템포 차이"
      },
      {
        "id": "choice-4",
        "label": "악기 수"
      }
    ],
    "answer": "choice-2",
    "explanation": "전조는 새로운 조의 기능과 종지가 더 지속적으로 확립된다."
  },
  {
    "id": "harmony.checkpoint.12.1",
    "part": 12,
    "targetLessonId": "harmony.lesson.modal-interchange.lesson",
    "prompt": "모달 인터체인지의 핵심은?",
    "options": [
      {
        "id": "choice-1",
        "label": "완전5도 위 조로 전조"
      },
      {
        "id": "choice-2",
        "label": "모든 코드를 7화음으로 변경"
      },
      {
        "id": "choice-3",
        "label": "조표를 제거"
      },
      {
        "id": "choice-4",
        "label": "같은 으뜸음의 다른 모드에서 화음을 차용"
      }
    ],
    "answer": "choice-4",
    "explanation": "평행조/평행모드에서 색채 화음을 빌려온다."
  },
  {
    "id": "harmony.checkpoint.12.2",
    "part": 12,
    "targetLessonId": "harmony.lesson.modal-interchange.lesson",
    "prompt": "C장조에서 흔한 차용화음은?",
    "options": [
      {
        "id": "choice-1",
        "label": "G(V)"
      },
      {
        "id": "choice-2",
        "label": "Am(vi)"
      },
      {
        "id": "choice-3",
        "label": "Fm(iv)"
      },
      {
        "id": "choice-4",
        "label": "Dm(ii)"
      }
    ],
    "answer": "choice-3",
    "explanation": "Fm은 C단조에서 빌린 iv다."
  },
  {
    "id": "harmony.checkpoint.12.3",
    "part": 12,
    "targetLessonId": "harmony.lesson.neapolitan-sixth.lesson",
    "prompt": "나폴리6화음의 기본은?",
    "options": [
      {
        "id": "choice-1",
        "label": "증4화음"
      },
      {
        "id": "choice-2",
        "label": "♭II 장3화음의 제1전위"
      },
      {
        "id": "choice-3",
        "label": "V7의 제3전위"
      },
      {
        "id": "choice-4",
        "label": "vi의 기본형"
      }
    ],
    "answer": "choice-2",
    "explanation": "전통적으로 ♭II의 장화음을 1전위로 쓰는 경우가 많다."
  },
  {
    "id": "harmony.checkpoint.12.4",
    "part": 12,
    "targetLessonId": "harmony.lesson.augmented-sixth.lesson",
    "prompt": "증6화음의 핵심 외성은?",
    "options": [
      {
        "id": "choice-1",
        "label": "♭6과 ♯4"
      },
      {
        "id": "choice-2",
        "label": "1과 5"
      },
      {
        "id": "choice-3",
        "label": "2와 7"
      },
      {
        "id": "choice-4",
        "label": "3과 6"
      }
    ],
    "answer": "choice-1",
    "explanation": "두 음이 바깥 방향으로 벌어져 V의 근음으로 해결한다."
  },
  {
    "id": "harmony.checkpoint.13.1",
    "part": 13,
    "targetLessonId": "harmony.lesson.modulation-concept.lesson",
    "prompt": "전조란?",
    "options": [
      {
        "id": "choice-1",
        "label": "템포를 바꾸는 것"
      },
      {
        "id": "choice-2",
        "label": "악기를 바꾸는 것"
      },
      {
        "id": "choice-3",
        "label": "조성 중심이 다른 조로 이동하는 것"
      },
      {
        "id": "choice-4",
        "label": "같은 화음을 반복하는 것"
      }
    ],
    "answer": "choice-3",
    "explanation": "새로운 조의 기능과 종지가 일정 시간 확립된다."
  },
  {
    "id": "harmony.checkpoint.13.2",
    "part": 13,
    "targetLessonId": "harmony.lesson.pivot-chord-modulation.lesson",
    "prompt": "공통화음 전조의 피벗 화음은?",
    "options": [
      {
        "id": "choice-1",
        "label": "항상 감7화음"
      },
      {
        "id": "choice-2",
        "label": "두 조에 모두 속하는 화음"
      },
      {
        "id": "choice-3",
        "label": "두 조 어디에도 없는 화음"
      },
      {
        "id": "choice-4",
        "label": "항상 V7"
      }
    ],
    "answer": "choice-2",
    "explanation": "하나의 화음을 앞뒤 조에서 다르게 해석한다."
  },
  {
    "id": "harmony.checkpoint.13.3",
    "part": 13,
    "targetLessonId": "harmony.lesson.direct-modulation.lesson",
    "prompt": "직접 전조의 특징은?",
    "options": [
      {
        "id": "choice-1",
        "label": "공통화음 없이 곧바로 새 조로 이동"
      },
      {
        "id": "choice-2",
        "label": "반드시 공통화음 사용"
      },
      {
        "id": "choice-3",
        "label": "항상 반음 위로만 이동"
      },
      {
        "id": "choice-4",
        "label": "조성이 변하지 않음"
      }
    ],
    "answer": "choice-1",
    "explanation": "강한 대비를 만들 수 있다."
  },
  {
    "id": "harmony.checkpoint.13.4",
    "part": 13,
    "targetLessonId": "harmony.lesson.common-tone-modulation.lesson",
    "prompt": "공통음 전조에서 연결고리는?",
    "options": [
      {
        "id": "choice-1",
        "label": "같은 템포"
      },
      {
        "id": "choice-2",
        "label": "같은 리듬만"
      },
      {
        "id": "choice-3",
        "label": "같은 조표만"
      },
      {
        "id": "choice-4",
        "label": "두 조가 공유하는 하나의 음"
      }
    ],
    "answer": "choice-4",
    "explanation": "한 음을 지속하며 주변 화음의 기능을 바꾼다."
  },
  {
    "id": "harmony.checkpoint.14.1",
    "part": 14,
    "targetLessonId": "harmony.lesson.advanced-roman-analysis.lesson",
    "prompt": "화성 분석의 첫 단계로 가장 적절한 것은?",
    "options": [
      {
        "id": "choice-1",
        "label": "악기 수 세기"
      },
      {
        "id": "choice-2",
        "label": "조성 파악"
      },
      {
        "id": "choice-3",
        "label": "모든 비화성음 이름부터 지정"
      },
      {
        "id": "choice-4",
        "label": "템포 측정"
      }
    ],
    "answer": "choice-2",
    "explanation": "조성을 알아야 로마숫자와 기능을 올바르게 판단할 수 있다."
  },
  {
    "id": "harmony.checkpoint.14.2",
    "part": 14,
    "targetLessonId": "harmony.lesson.advanced-roman-analysis.lesson",
    "prompt": "로마숫자 분석이 답하는 질문은?",
    "options": [
      {
        "id": "choice-1",
        "label": "이 화음이 조성의 몇 도에 있는가"
      },
      {
        "id": "choice-2",
        "label": "이 곡은 몇 BPM인가"
      },
      {
        "id": "choice-3",
        "label": "연주자는 누구인가"
      },
      {
        "id": "choice-4",
        "label": "마디 수는 몇 개인가"
      }
    ],
    "answer": "choice-1",
    "explanation": "화음의 조성 내 상대적 위치와 성질을 표현한다."
  },
  {
    "id": "harmony.checkpoint.14.3",
    "part": 14,
    "targetLessonId": "harmony.lesson.advanced-function-analysis.lesson",
    "prompt": "기능 분석의 장점은?",
    "options": [
      {
        "id": "choice-1",
        "label": "음표 길이를 계산한다"
      },
      {
        "id": "choice-2",
        "label": "조표를 없앤다"
      },
      {
        "id": "choice-3",
        "label": "악기 음색을 정한다"
      },
      {
        "id": "choice-4",
        "label": "여러 화음을 더 큰 역할 단위로 묶는다"
      }
    ],
    "answer": "choice-4",
    "explanation": "T/PD/D 같은 거시적 방향을 파악한다."
  },
  {
    "id": "harmony.checkpoint.14.4",
    "part": 14,
    "targetLessonId": "harmony.lesson.piece-analysis.lesson",
    "prompt": "악곡 분석에서 종지가 중요한 이유는?",
    "options": [
      {
        "id": "choice-1",
        "label": "리듬을 단순화한다"
      },
      {
        "id": "choice-2",
        "label": "음정을 바꾼다"
      },
      {
        "id": "choice-3",
        "label": "악절과 형식의 경계를 드러낸다"
      },
      {
        "id": "choice-4",
        "label": "모든 전조를 금지한다"
      }
    ],
    "answer": "choice-3",
    "explanation": "종지 강도와 위치는 구조적 위계를 보여준다."
  },
  {
    "id": "harmony.checkpoint.15.1",
    "part": 15,
    "targetLessonId": "harmony.lesson.voice-leading-basics.lesson",
    "prompt": "공통음이 있는 두 화음을 연결할 때 일반적인 원칙은?",
    "options": [
      {
        "id": "choice-1",
        "label": "공통음을 유지하고 나머지는 가까운 음으로 이동"
      },
      {
        "id": "choice-2",
        "label": "모든 성부를 도약"
      },
      {
        "id": "choice-3",
        "label": "항상 같은 방향으로 이동"
      },
      {
        "id": "choice-4",
        "label": "베이스를 고정"
      }
    ],
    "answer": "choice-1",
    "explanation": "최소 이동은 부드러운 성부진행에 도움이 된다."
  },
  {
    "id": "harmony.checkpoint.15.2",
    "part": 15,
    "targetLessonId": "harmony.lesson.voice-leading",
    "prompt": "전통 4성부에서 피하는 것은?",
    "options": [
      {
        "id": "choice-1",
        "label": "반대진행"
      },
      {
        "id": "choice-2",
        "label": "공통음 유지"
      },
      {
        "id": "choice-3",
        "label": "순차진행"
      },
      {
        "id": "choice-4",
        "label": "병행5도와 병행8도"
      }
    ],
    "answer": "choice-4",
    "explanation": "성부 독립성을 약화시키는 대표적 금지 병행이다."
  },
  {
    "id": "harmony.checkpoint.15.3",
    "part": 15,
    "targetLessonId": "harmony.lesson.voice-spacing.lesson",
    "prompt": "S-A와 A-T의 일반적 간격 원칙은?",
    "options": [
      {
        "id": "choice-1",
        "label": "항상 10도 이상"
      },
      {
        "id": "choice-2",
        "label": "제한 없음"
      },
      {
        "id": "choice-3",
        "label": "각각 옥타브 이내"
      },
      {
        "id": "choice-4",
        "label": "항상 2도"
      }
    ],
    "answer": "choice-3",
    "explanation": "상3성부의 인접 성부 간격은 보통 옥타브 이내다."
  },
  {
    "id": "harmony.checkpoint.15.4",
    "part": 15,
    "targetLessonId": "harmony.lesson.cadence-writing.lesson",
    "prompt": "V7의 화음 7음은 일반적으로?",
    "options": [
      {
        "id": "choice-1",
        "label": "반드시 5도 상행"
      },
      {
        "id": "choice-2",
        "label": "순차 하행"
      },
      {
        "id": "choice-3",
        "label": "도약 상행"
      },
      {
        "id": "choice-4",
        "label": "그대로 반복만"
      }
    ],
    "answer": "choice-2",
    "explanation": "7음의 불협화는 보통 한 음 아래로 해결한다."
  },
  {
    "id": "harmony.checkpoint.16.1",
    "part": 16,
    "targetLessonId": "harmony.lesson.chorale-analysis.lesson",
    "prompt": "코랄 분석에서 함께 봐야 할 것은?",
    "options": [
      {
        "id": "choice-1",
        "label": "코드명만"
      },
      {
        "id": "choice-2",
        "label": "리듬만"
      },
      {
        "id": "choice-3",
        "label": "악기 편성만"
      },
      {
        "id": "choice-4",
        "label": "기능·비화성음·성부진행·종지"
      }
    ],
    "answer": "choice-4",
    "explanation": "코랄은 여러 화성 요소를 통합해 보는 자료다."
  },
  {
    "id": "harmony.checkpoint.16.2",
    "part": 16,
    "targetLessonId": "harmony.lesson.classical-harmony.lesson",
    "prompt": "고전주의 화성의 대표적 특징은?",
    "options": [
      {
        "id": "choice-1",
        "label": "무작위 화음"
      },
      {
        "id": "choice-2",
        "label": "전조 금지"
      },
      {
        "id": "choice-3",
        "label": "명확한 기능과 종지 구조"
      },
      {
        "id": "choice-4",
        "label": "조성 중심의 완전한 부재"
      }
    ],
    "answer": "choice-3",
    "explanation": "기능적 명료성과 균형 잡힌 악절이 중요하다."
  },
  {
    "id": "harmony.checkpoint.16.3",
    "part": 16,
    "targetLessonId": "harmony.lesson.romantic-harmony.lesson",
    "prompt": "낭만주의 화성에서 증가하는 요소는?",
    "options": [
      {
        "id": "choice-1",
        "label": "단일 코드 반복만"
      },
      {
        "id": "choice-2",
        "label": "반음계와 색채적 전조"
      },
      {
        "id": "choice-3",
        "label": "모든 변화표 제거"
      },
      {
        "id": "choice-4",
        "label": "종지 완전 제거"
      }
    ],
    "answer": "choice-2",
    "explanation": "차용화음·공통음·반음계적 재해석이 확대된다."
  },
  {
    "id": "harmony.checkpoint.16.4",
    "part": 16,
    "targetLessonId": "harmony.lesson.pop-harmony.lesson",
    "prompt": "현대 대중음악 분석에 필요한 관점은?",
    "options": [
      {
        "id": "choice-1",
        "label": "기능과 루프/모달 색채를 함께 본다"
      },
      {
        "id": "choice-2",
        "label": "기능화성만 절대적으로 적용"
      },
      {
        "id": "choice-3",
        "label": "로마숫자를 쓰지 않는다"
      },
      {
        "id": "choice-4",
        "label": "멜로디는 무시한다"
      }
    ],
    "answer": "choice-1",
    "explanation": "기능적이지 않은 반복과 색채 진행도 함께 고려해야 한다."
  }
] as const;

export function attachLegacyCheckpoints(source: Book): Book {
  const book=structuredClone(source);
  const lessons=book.parts.flatMap((part)=>part.lessons);
  for(const checkpoint of legacyCheckpointMappings){
    const lesson=lessons.find((item)=>item.id===checkpoint.targetLessonId);
    if(!lesson)throw new Error(`Legacy checkpoint target not found: ${checkpoint.targetLessonId}`);
    const block={id:checkpoint.id,blockVersion,type:'assessment.multiple-choice' as const,objectiveRefs:[lesson.objectives[0].id],data:{prompt:checkpoint.prompt,options:checkpoint.options.map((option)=>({...option})),answer:checkpoint.answer,explanation:checkpoint.explanation}};
    lesson.blocks.push(block);
    if(lesson.completion.type==='required-blocks')lesson.completion.blockRefs.push(block.id);
  }
  return book;
}
