import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { PlaybackSessionController } from '@interactive-textbook/engine-player';
import { synthesizePitches } from './musicAudio';
import { createInterval, keyboardGeometry, midiToPitch, pitchName, pitchToMidi, validateChordSelection, validatePitchPair, type IntervalQuality, type Pitch } from '@interactive-textbook/subject-music';
interface PairInput { pairs?: Pitch[][]; initial?: Pitch[]; range?: { fromMidi: number; toMidi: number }; target?: { degree: number; quality: IntervalQuality }; targetPitches?: Pitch[]; }
interface Props { tool: string; title: string; input: PairInput; onComplete?: (response: { pitches: Pitch[]; semitones: number; correct: boolean; attempts: number }) => void; }
const playback = new PlaybackSessionController();
const staffStep = { C: 0, D: 1, E: 2, F: 3, G: 4, A: 5, B: 6 } as const;
function staffY(pitch: Pitch) { const diatonic = pitch.octave * 7 + staffStep[pitch.step]; const e4 = 4 * 7 + staffStep.E; return 90 - (diatonic - e4) * 6; }
function ledgerLines(y: number) { const lines: number[] = []; if (y >= 102) for (let line = 102; line <= y; line += 12) lines.push(line); if (y <= 30) for (let line = 30; line >= y; line -= 12) lines.push(line); return lines; }

export function Staff({ pitches = [], groups, activeMidi }: { pitches?: Pitch[]; groups?: Pitch[][]; activeMidi?: number }) {
  const columns = groups ?? pitches.map((pitch) => [pitch]); const allPitches = columns.flat(); const spacing = columns.length > 1 ? Math.min(140, 240 / (columns.length - 1)) : 0; const startX = 240 - spacing * (columns.length - 1) / 2;
  return <svg className="staff" viewBox="0 0 420 130" role="img" aria-label={`악보: ${allPitches.map(pitchName).join(', ')}`}>
    {[42, 54, 66, 78, 90].map((y) => <line key={y} x1="24" x2="396" y1={y} y2={y} />)}<text x="36" y="88" className="clef">𝄞</text>
    {columns.map((column, columnIndex) => { const x = startX + columnIndex * spacing; return column.map((pitch, pitchIndex) => { const midi = pitchToMidi(pitch); const y = staffY(pitch); return <g key={`${pitchName(pitch)}-${columnIndex}-${pitchIndex}`} className={midi === activeMidi ? 'note active' : 'note'}>{ledgerLines(y).map((line) => <line key={line} x1={x - 16} x2={x + 16} y1={line} y2={line} />)}<ellipse cx={x} cy={y} rx="10" ry="7" /><line x1={x + 10} x2={x + 10} y1={y} y2={y - 40} />{pitch.alter !== 0 && <text x={x - 24} y={y + 6}>{pitch.alter < 0 ? '♭' : '♯'}</text>}</g>; }); })}
  </svg>;
}
export function Keyboard({ selected, activeMidi, onSelect, fromMidi = 60, toMidi = 72 }: { selected: Pitch[]; activeMidi?: number; onSelect?: (pitch: Pitch) => void; fromMidi?: number; toMidi?: number }) {
  const keys = keyboardGeometry(fromMidi, toMidi); const width = 100 / keys.filter((key) => !key.black).length; const [focusIndex, setFocusIndex] = useState(0); const keyRefs = useRef<Array<HTMLButtonElement | null>>([]);
  useEffect(() => { setFocusIndex((current) => Math.min(current, Math.max(keys.length - 1, 0))); }, [keys.length]);
  const moveFocus = (index: number) => { const next = Math.max(0, Math.min(index, keys.length - 1)); setFocusIndex(next); keyRefs.current[next]?.focus(); };
  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { let next: number | undefined; if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = index + 1; if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = index - 1; if (event.key === 'Home') next = 0; if (event.key === 'End') next = keys.length - 1; if (next !== undefined) { event.preventDefault(); moveFocus(next); } };
  return <div className="keyboard" role="group" aria-label={`${pitchName(midiToPitch(fromMidi))}부터 ${pitchName(midiToPitch(toMidi))}까지 피아노 건반. 좌우 방향키로 이동하고 Enter 또는 Space로 선택하세요.`}>{keys.map((key, index) => { const selectedIndex = selected.findIndex((pitch) => pitchToMidi(pitch) === key.midi); const style = key.black ? { left: `${(key.whiteIndex + .72) * width}%`, width: `${width * .56}%` } : { left: `${key.whiteIndex * width}%`, width: `${width}%` }; return <button type="button" key={key.midi} ref={(element) => { keyRefs.current[index] = element; }} tabIndex={index === focusIndex ? 0 : -1} className={`piano-key ${key.black ? 'black' : 'white'} ${selectedIndex >= 0 ? 'selected' : ''} ${activeMidi === key.midi ? 'playing' : ''}`} style={style} aria-label={`${pitchName(key.pitch)}${selectedIndex >= 0 ? `, ${selectedIndex + 1}번째 선택` : ''}`} aria-pressed={selectedIndex >= 0} onFocus={() => setFocusIndex(index)} onKeyDown={(event) => handleKeyDown(event, index)} onClick={() => onSelect?.(key.pitch)}><span>{key.black ? pitchName(key.pitch).replace(/\d/g, '') : key.pitch.step}</span>{selectedIndex >= 0 && <b>{selectedIndex + 1}</b>}</button>; })}</div>;
}
function usePitchAudio() {
  const context = useRef<AudioContext | null>(null); const [activeMidi, setActiveMidi] = useState<number>(); const [playing, setPlaying] = useState(false);
  const stop = () => { playback.stop(); setActiveMidi(undefined); setPlaying(false); };
  const play = async (pitches: Pitch[]) => { stop(); const session = playback.start('harmony.audio.semitone'); setPlaying(true); const audio = context.current ?? new AudioContext(); context.current = audio; await audio.resume(); for (const pitch of pitches) { if (session.signal.aborted) return; setActiveMidi(pitchToMidi(pitch)); synthesizePitches(audio, [pitch], 450, .18); await new Promise((resolve) => setTimeout(resolve, 520)); } if (!session.signal.aborted) stop(); };
  return { activeMidi, playing, play, stop };
}
export function MusicActivity({ tool, title, input, onComplete }: Props) {
  const [selected, setSelected] = useState<Pitch[]>(input.initial ?? input.pairs?.[0] ?? []); const [pairIndex, setPairIndex] = useState(0); const [attempts, setAttempts] = useState(0); const [feedback, setFeedback] = useState(''); const audio = usePitchAudio(); const pairs = input.pairs ?? []; const displayed = tool === 'pitch-pair-viewer' ? (pairs[pairIndex] ?? []) : selected;
  const interactive = ['semitone-explorer', 'interval-builder', 'chord-builder'].includes(tool);
  const choose = (pitch: Pitch) => { if (interactive) { setSelected((current) => { if (tool === 'interval-builder') return [current[0] ?? pitch, pitch]; if (tool === 'chord-builder') { const exists = current.some((item) => pitchToMidi(item) === pitchToMidi(pitch)); return exists ? current.filter((item) => pitchToMidi(item) !== pitchToMidi(pitch)) : current.length < 3 ? [...current, pitch] : [pitch]; } return current.length >= 2 ? [pitch] : [...current, pitch]; }); setFeedback(''); } };
  const check = () => { const count = attempts + 1; setAttempts(count); if (tool === 'chord-builder' && input.targetPitches) { const result = validateChordSelection(input.targetPitches, selected); setFeedback(result.message); if (result.correct) onComplete?.({ pitches: selected, semitones: 0, correct: true, attempts: count }); return; } if (selected.length !== 2) { setFeedback('두 음을 차례로 선택하세요.'); return; } if (tool === 'interval-builder' && input.target) { const interval = createInterval(selected[0], selected[1]); const correct = interval.degree === input.target.degree && interval.quality === input.target.quality; setFeedback(correct ? `정답입니다. ${interval.semitones}반음의 완전${interval.degree}도입니다.` : `현재 ${interval.degree}도, ${interval.semitones}반음입니다. 도수와 반음 수를 함께 확인하세요.`); if (correct) onComplete?.({ pitches: selected, semitones: interval.semitones, correct, attempts: count }); return; } const result = validatePitchPair(selected[0], selected[1]); setFeedback(result.message); if (result.correct) onComplete?.({ pitches: selected, semitones: result.semitones, correct: true, attempts: count }); };
  const chordDisplay = tool === 'chord-builder' || displayed.length > 2;
  return <section className="music-activity" aria-labelledby={`music-${tool}`}><p className="section-label">MUSIC · {tool}</p><h2 id={`music-${tool}`}>{title}</h2><Staff pitches={chordDisplay ? [] : displayed} groups={chordDisplay ? [displayed] : undefined} activeMidi={audio.activeMidi} /><Keyboard selected={displayed} activeMidi={audio.activeMidi} onSelect={interactive ? choose : undefined} fromMidi={input.range?.fromMidi} toMidi={input.range?.toMidi} />{tool === 'pitch-pair-viewer' && <div className="pair-tabs">{pairs.map((pair, index) => <button type="button" key={index} aria-pressed={pairIndex === index} onClick={() => setPairIndex(index)}>{pair.map(pitchName).join('–')}</button>)}</div>}<div className="activity-controls"><button type="button" onClick={() => audio.play(displayed)}>{audio.playing ? '처음부터 듣기' : `▶ ${chordDisplay ? '화음' : '두 음'} 듣기`}</button>{audio.playing && <button type="button" onClick={audio.stop}>■ 중지</button>}{interactive && <><button type="button" onClick={check}>판정하기</button><button type="button" className="secondary" onClick={() => { setSelected(tool === 'interval-builder' ? input.initial ?? [] : []); setFeedback(''); audio.stop(); }}>초기화</button></>}</div><p className="play-status" aria-live="polite">{audio.playing && audio.activeMidi !== undefined ? `${pitchName(midiToPitch(audio.activeMidi))} 재생 중` : feedback}</p></section>;
}
