import { useRef, useState } from 'react';
import { PlaybackSessionController } from '@interactive-textbook/engine-player';
import { keyboardGeometry, midiToPitch, pitchName, pitchToMidi, validatePitchPair, type Pitch } from '@interactive-textbook/subject-music';
interface PairInput { pairs?: Pitch[][]; initial?: Pitch[]; range?: { fromMidi: number; toMidi: number }; }
interface Props { tool: string; title: string; input: PairInput; onComplete?: (response: { pitches: Pitch[]; semitones: number; correct: boolean; attempts: number }) => void; }
const playback = new PlaybackSessionController();

function Staff({ pitches, activeMidi }: { pitches: Pitch[]; activeMidi?: number }) {
  return <svg className="staff" viewBox="0 0 420 130" role="img" aria-label={`악보: ${pitches.map(pitchName).join(', ')}`}>
    {[42, 54, 66, 78, 90].map((y) => <line key={y} x1="24" x2="396" y1={y} y2={y} />)}<text x="36" y="88" className="clef">𝄞</text>
    {pitches.map((pitch, index) => { const midi = pitchToMidi(pitch); const x = 140 + index * 100; const y = 90 - (midi - 60) * 3; return <g key={`${pitchName(pitch)}-${index}`} className={midi === activeMidi ? 'note active' : 'note'}><ellipse cx={x} cy={y} rx="10" ry="7" /><line x1={x + 10} x2={x + 10} y1={y} y2={y - 40} />{pitch.alter !== 0 && <text x={x - 24} y={y + 6}>{pitch.alter < 0 ? '♭' : '♯'}</text>}</g>; })}
  </svg>;
}
function Keyboard({ selected, activeMidi, onSelect, fromMidi = 60, toMidi = 72 }: { selected: Pitch[]; activeMidi?: number; onSelect?: (pitch: Pitch) => void; fromMidi?: number; toMidi?: number }) {
  const keys = keyboardGeometry(fromMidi, toMidi); const width = 100 / keys.filter((key) => !key.black).length;
  return <div className="keyboard" role="group" aria-label="C4부터 C5까지 피아노 건반">{keys.map((key) => { const selectedIndex = selected.findIndex((pitch) => pitchToMidi(pitch) === key.midi); const style = key.black ? { left: `${(key.whiteIndex + .72) * width}%`, width: `${width * .56}%` } : { left: `${key.whiteIndex * width}%`, width: `${width}%` }; return <button type="button" key={key.midi} className={`piano-key ${key.black ? 'black' : 'white'} ${selectedIndex >= 0 ? 'selected' : ''} ${activeMidi === key.midi ? 'playing' : ''}`} style={style} aria-label={`${pitchName(key.pitch)}${selectedIndex >= 0 ? `, ${selectedIndex + 1}번째 선택` : ''}`} aria-pressed={selectedIndex >= 0} onClick={() => onSelect?.(key.pitch)}><span>{key.black ? pitchName(key.pitch).replace(/\d/g, '') : key.pitch.step}</span>{selectedIndex >= 0 && <b>{selectedIndex + 1}</b>}</button>; })}</div>;
}
function usePitchAudio() {
  const context = useRef<AudioContext | null>(null); const [activeMidi, setActiveMidi] = useState<number>(); const [playing, setPlaying] = useState(false);
  const stop = () => { playback.stop(); setActiveMidi(undefined); setPlaying(false); };
  const play = async (pitches: Pitch[]) => { stop(); const session = playback.start('harmony.audio.semitone'); setPlaying(true); const audio = context.current ?? new AudioContext(); context.current = audio; await audio.resume(); for (const pitch of pitches) { if (session.signal.aborted) return; const midi = pitchToMidi(pitch); setActiveMidi(midi); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.frequency.value = 440 * 2 ** ((midi - 69) / 12); gain.gain.setValueAtTime(.0001, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.18, audio.currentTime + .02); gain.gain.exponentialRampToValueAtTime(.0001, audio.currentTime + .42); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .45); await new Promise((resolve) => setTimeout(resolve, 520)); } if (!session.signal.aborted) stop(); };
  return { activeMidi, playing, play, stop };
}
export function MusicActivity({ tool, title, input, onComplete }: Props) {
  const [selected, setSelected] = useState<Pitch[]>(input.initial ?? input.pairs?.[0] ?? []); const [pairIndex, setPairIndex] = useState(0); const [attempts, setAttempts] = useState(0); const [feedback, setFeedback] = useState(''); const audio = usePitchAudio(); const pairs = input.pairs ?? []; const displayed = tool === 'pitch-pair-viewer' ? (pairs[pairIndex] ?? []) : selected;
  const choose = (pitch: Pitch) => { if (tool === 'semitone-explorer') { setSelected((current) => current.length >= 2 ? [pitch] : [...current, pitch]); setFeedback(''); } };
  const check = () => { if (selected.length !== 2) { setFeedback('두 음을 차례로 선택하세요.'); return; } const result = validatePitchPair(selected[0], selected[1]); const count = attempts + 1; setAttempts(count); setFeedback(result.message); if (result.correct) onComplete?.({ pitches: selected, semitones: result.semitones, correct: true, attempts: count }); };
  return <section className="music-activity" aria-labelledby={`music-${tool}`}><p className="section-label">MUSIC · {tool}</p><h2 id={`music-${tool}`}>{title}</h2><Staff pitches={displayed} activeMidi={audio.activeMidi} /><Keyboard selected={displayed} activeMidi={audio.activeMidi} onSelect={tool === 'semitone-explorer' ? choose : undefined} fromMidi={input.range?.fromMidi} toMidi={input.range?.toMidi} />{tool === 'pitch-pair-viewer' && <div className="pair-tabs">{pairs.map((pair, index) => <button type="button" key={index} aria-pressed={pairIndex === index} onClick={() => setPairIndex(index)}>{pair.map(pitchName).join('–')}</button>)}</div>}<div className="activity-controls"><button type="button" onClick={() => audio.play(displayed)}>{audio.playing ? '처음부터 듣기' : '▶ 두 음 듣기'}</button>{audio.playing && <button type="button" onClick={audio.stop}>■ 중지</button>}{tool === 'semitone-explorer' && <><button type="button" onClick={check}>거리 확인</button><button type="button" className="secondary" onClick={() => { setSelected([]); setFeedback(''); audio.stop(); }}>초기화</button></>}</div><p className="play-status" aria-live="polite">{audio.playing && audio.activeMidi !== undefined ? `${pitchName(midiToPitch(audio.activeMidi))} 재생 중` : feedback}</p></section>;
}
