import { useRef, useState } from 'react';
import { cadenceFeedback, pitchName, pitchToMidi, type CadenceProgression, type CadenceType } from '@interactive-textbook/subject-music';
import { PlaybackSessionController } from '@interactive-textbook/engine-player';
import { Keyboard, Staff } from './MusicActivity';
import { synthesizePitches } from './musicAudio';
interface Props { tool: string; title: string; input: { progressions: CadenceProgression[]; target?: CadenceType; hideAnalysisUntilAnswer?: boolean }; onComplete?: (value: unknown) => void; }
const sessions = new PlaybackSessionController();
const cadenceNames: Record<CadenceType, string> = { authentic: '정격종지', half: '반종지', plagal: '변격종지', deceptive: '기만종지' };
export function ProgressionActivity({ tool, title, input, onComplete }: Props) {
  const availableProgressions = tool === 'cadence-listener' && input.target ? input.progressions.filter((item) => item.cadenceType === input.target) : input.progressions;
  const [exampleIndex, setExampleIndex] = useState(0); const [stepIndex, setStepIndex] = useState(0); const [nextStepIndex, setNextStepIndex] = useState(0); const [playing, setPlaying] = useState(false); const [feedback, setFeedback] = useState(''); const [answered, setAnswered] = useState(false); const [selectedAnswer, setSelectedAnswer] = useState<CadenceType>(); const context = useRef<AudioContext | null>(null); const progression = availableProgressions[exampleIndex]; const chord = progression.steps[stepIndex]?.chord; const analysisVisible = !input.hideAnalysisUntilAnswer || answered;
  const progressionMidis = progression.steps.flatMap((step) => step.chord.pitches.map(pitchToMidi)); const fromMidi = progressionMidis.length ? Math.min(...progressionMidis) : 60; const toMidi = progressionMidis.length ? Math.max(...progressionMidis) : 72;
  const stop = () => { sessions.stop(); setPlaying(false); };
  const soundChord = async (index: number, session: ReturnType<typeof sessions.start>) => { const step = progression.steps[index]; if (!step || session.signal.aborted) return; setStepIndex(index); const audio = context.current ?? new AudioContext(); context.current = audio; await audio.resume(); synthesizePitches(audio, step.chord.pitches, step.durationMs, .1); await new Promise((resolve) => setTimeout(resolve, step.durationMs)); };
  const playAll = async () => { stop(); const session = sessions.start(progression.id); setPlaying(true); for (let index = 0; index < progression.steps.length; index += 1) { await soundChord(index, session); if (session.signal.aborted) return; } setNextStepIndex(0); setPlaying(false); };
  const playStep = async () => { stop(); const current = nextStepIndex; const session = sessions.start(progression.id); setPlaying(true); await soundChord(current, session); if (!session.signal.aborted) { setNextStepIndex((current + 1) % progression.steps.length); setPlaying(false); } };
  const answer = (selected: CadenceType) => { if (!input.target) return; const result = cadenceFeedback(input.target, selected); setSelectedAnswer(selected); setAnswered(true); setFeedback(result.message); if (result.correct) onComplete?.({ response: selected, correct: true, attempts: 1 }); };
  return <section className="music-activity"><p className="section-label">MUSIC · {tool}</p><h2>{title}</h2>{availableProgressions.length > 1 && <div className="pair-tabs">{availableProgressions.map((item, index) => <button type="button" key={item.id} aria-pressed={index === exampleIndex} onClick={() => { stop(); setExampleIndex(index); setStepIndex(0); setNextStepIndex(0); }}>{index + 1}번 진행</button>)}</div>}{analysisVisible ? <><Staff groups={chord ? [chord.pitches] : []} /><Keyboard selected={chord?.pitches ?? []} fromMidi={fromMidi} toMidi={toMidi} /></> : <p className="listening-prompt">악보와 화음 이름은 답을 고른 뒤 공개됩니다. 먼저 소리에 집중해 보세요.</p>}<p className="step-indicator" aria-live="polite">{playing ? '재생 중 · ' : ''}{stepIndex + 1} / {progression.steps.length}{analysisVisible ? ` · ${chord?.symbol}` : ''}</p><div className="activity-controls"><button type="button" onClick={playAll}>▶ 전체 진행 듣기</button><button type="button" onClick={playStep}>▶ 다음 화음 듣기 · {nextStepIndex + 1}/{progression.steps.length}</button>{playing && <button type="button" onClick={stop}>■ 중지</button>}</div>{tool === 'cadence-listener' && <div className="answer-grid">{(Object.keys(cadenceNames) as CadenceType[]).map((type) => <button type="button" key={type} aria-pressed={type === selectedAnswer} onClick={() => answer(type)}>{cadenceNames[type]}</button>)}</div>}<p className="play-status" aria-live="polite">{feedback || (analysisVisible && chord ? `${chord.symbol}: ${chord.pitches.map(pitchName).join(', ')}` : '')}</p></section>;
}
